### ISSUE TITLE
Can't Edit a scene

### ISSUE THREAD

**Issue by Hyrules** [Hyrules/WinHue3#1]
When I try to save the scene after editing, I get this strange error. Any
ideas?

Creator : fiveseven808

Right click on scene -> edit
Click on a few lights under "Selected Lights" 
Uncheck "on" for some of those lights
Click "Save Scene"

**Comment by Hyrules** [comment]
I don't understand why but the program seems to add a blank message from the bridge. Can you also tell me what API version you have ? I'm still looking into this.
EDIT : did you install the latest beta 16 (attachment to my previous message) and try to edit the scene ? I'm seaching for specific logging I added but I cannot find them. They are not conditionnal so if you tried to edit the scene and save it they should appear.

**Comment by fiveseven808** [comment]
I installed the latest beta, however I noticed that I see nothing in the logs as well. Should I make a video or something?

**Comment by Hyrules** [comment]
No don't worry about it for now. I'm currently remaking the WinHue communication module. I should get a  better understanding of what happens. I should have something to test soon.

**Comment by fiveseven808** [comment]
I hate to say it, but I can't find the scene I was looking to edit. Maybe it got deleted and WinHue never picked up on the change until now?

**Comment by Hyrules** [comment]
I would be suprised of that. WinHue always query the bridge for all objects
every time. It never stores the current scenes or anything beside the
pairing settings and app settings. if you ever find it or find this bug
again just let me know. Most likely it was recycled by the bridge. It can
happen if there are too many scenes or if it was marked to be recycled.
