### ISSUE TITLE
Instantly crashing after pairing, System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by KoetseJ** [Hyrules/WinHue3#104]
I tried re-pairing, it causes the same issue again.

Here is the log file, I removed the lines with the API keys
[WinHue3 2017-08-19.txt](https://github.com/Hyrules/WinHue3/files/1236398/WinHue3.2017-08-19.txt)

**Comment by Hyrules** [comment]
I see where it crashes and where the null is generated but i don't understand why. if you remove some lines from the log that won't help me debug. Those lines contains information I need to understand why the application has crashed such as the version of the api and firmware. The whole json in itself helps me debug. I can use it to test function and see what happens.

You can try this version. I know it wont fix the problem but it will most likely give me the information I need to debug. I ask this time that you do not remove lines from the debug log. I will take the log and remove it once I have it. if you dont feel like putting it here you can send it to me at hyrules at gmail.com.

[WinHue 3 RC 3 Setup.zip](https://github.com/Hyrules/WinHue3/files/1236431/WinHue.3.RC.3.Setup.zip)

**Comment by KoetseJ** [comment]
That version still crashes it, I emailed the full debug log to your email.

**Comment by Hyrules** [comment]
I'll take a look at your log and see if I can spot anything weird.

**Comment by Hyrules** [comment]
I think I have it. Try this version and let me know if this fixes it.

[WinHue 3 RC 3 Setup.zip](https://github.com/Hyrules/WinHue3/files/1237354/WinHue.3.RC.3.Setup.zip)

**Comment by KoetseJ** [comment]
This version is working, great!

**Comment by Hyrules** [comment]
Great ! I will add this fix to the next release. thanks.

**Comment by Hyrules** [comment]
Will be fixed in the next version.

**Comment by Hyrules** [comment]
Closing the issue. When the next version is released let me know if this is still an issue.
