### ISSUE TITLE
RC2 crashes when Advanced Creator is clicked

### ISSUE THREAD

**Issue by banksio** [Hyrules/WinHue3#106]
As the title says, whenever I click the _Advanced Creator_ button in the ribbon, the app throws an exception and crashes. [Here's the log](https://pastebin.com/f5cwZbLq).

**Comment by Hyrules** [comment]
Ok this one is easy. I forgot to add the the dll for the editor.

**Comment by Hyrules** [comment]
you can try the version in #105 it should fix this issue but not the other you reported.

**Comment by banksio** [comment]
Yup, works great. Thanks!

**Comment by banksio** [comment]
New issue, when clicking Clear in the ribbon in the Advanced Creator, the app crashes. [Here's the log](https://pastebin.com/T5mkdR2Y).

**Comment by Hyrules** [comment]
hmmm the error is cryptic really. It does not mean anything. Does this happen everytime or only in certain condition ?

**Comment by banksio** [comment]
It is quite strange, the error only occurs if the text blinking cursor is anywhere other than before the first character. So if the cursor is here `|{"na...` it will not crash but if the text cursor is anywhere else, for example here `{"|na...`, it will crash.

**Comment by Hyrules** [comment]
ok got it I can reproduce. I know where and why this happens...

**Comment by Hyrules** [comment]
Here you go.

[WinHue 3 RC 3 Setup.zip](https://github.com/Hyrules/WinHue3/files/1253273/WinHue.3.RC.3.Setup.zip)

**Comment by banksio** [comment]
Yep, works flawlessly now. Thanks! Anything else I find I'll be sure to post.

**Comment by Hyrules** [comment]
Closing this since it is fixed. I'll upload RC3 soon.
