### ISSUE TITLE
RC2 crashes immediately at startup

### ISSUE THREAD

**Issue by Craig-NZ** [Hyrules/WinHue3#107]
Removed the beta version and installed RC2 but when I try to run it immediately crashes.  Have attached the log file.
[WinHue3 2017-08-27.txt](https://github.com/Hyrules/WinHue3/files/1254187/WinHue3.2017-08-27.txt)

**Comment by Hyrules** [comment]
Can you try this version I think this has already been fixed.

[WinHue 3 RC 3 Setup.zip](https://github.com/Hyrules/WinHue3/files/1254414/WinHue.3.RC.3.Setup.zip)

**Comment by Craig-NZ** [comment]
That worked .. thanks heaps!
