### ISSUE TITLE
WinHue Crashes When Connection Lost

### ISSUE THREAD

**Issue by banksio** [Hyrules/WinHue3#110]
A crash occurs when connection to the Hue Bridge is lost after the program has been started, and the user tries to do something (e.g. turn on/off a light). [Log](https://pastebin.com/Jqsn8WtX), as always!

**Comment by Hyrules** [comment]
Yes I can reproduce that by unplugging the bridge after listing it's content.

**Comment by Hyrules** [comment]
Will be fixed in the next version.

**Comment by Hyrules** [comment]
I'll close this has this issue has will be fixed in the next version. Let me know if this is still and issue when the next version releases.
