### ISSUE TITLE
Motionsensor edit rules dialog is missing the "state" tree.

### ISSUE THREAD

**Issue by idefixx** [Hyrules/WinHue3#111]
I assume that when you add or edit a a rule condition for motions sensors the "state" node should be expended and contain the only important values "presence" and "lastupdate".

The node is empty though.

**Comment by Hyrules** [comment]
I'll take a look at this. thanks for reporting it.

**Comment by Hyrules** [comment]
Yep forgot to add some attributes to some states. I will correct this in RC3.

**Comment by Hyrules** [comment]
This has been corrected in the latest version.

**Comment by idefixx** [comment]
IF you mean "WinHue 3 RC 3 - 3.0.311.0" then, no its still the exact same issue.

The UI has changed slightly.
However the "Conditions" box for Motions Sensors contains an entry called state and its not expandable.
Nor does the list contain an entry "presence" or "lastupdate"

The path for a Motions Sensors sensor is /sensors/ID/state/presence and /sensors/ID/state/lastupdate.

**Comment by Hyrules** [comment]
This is not the same issue as last time. If you look at the list see #122
