### ISSUE TITLE
Manual entry of serial no

### ISSUE THREAD

**Issue by bohk** [Hyrules/WinHue3#114]
Hi

It is possible to make a manual entry of serial no on a light bulb?
My experience is that when a light bulb has identified itself to a bridge it will not do it again. It's easier to enter the number manually :-)

**Comment by Hyrules** [comment]
Not at the moment. There are some part of the documentation of the bridge that philips keeps hidden. I have just discovered recently a command to pair the light by proximity that I still don't have implemented. I know you can do this in the philips hue app but the API documentation does not give any information on how to do this.

**Comment by Hyrules** [comment]
I just found in the API hidden deep how to add lights by serial. I will try to implement it in the next version.

**Comment by bohk** [comment]
Cool - Thanks!!

Med venlig hilsen
Bo

**Comment by D1311** [comment]
Another feature i'm looking forward too.

**Comment by Hyrules** [comment]
Added to the next version. Will close it as the request has been fulfilled.
