### ISSUE TITLE
After configuring keyboard shortcuts. Winhue gets desynchronized from the bridges after the reboot.

### ISSUE THREAD

**Issue by djnyco** [Hyrules/WinHue3#117]
After configuring keyboard shortcuts. Winhue gets desynchronized from the bridges after the reboot.

I have to redo the configuration of the application, but if I do not create shortcuts all works properly.

Thanks

**Comment by Hyrules** [comment]
I have splited the settings in 3 files in the next release. Hotkeys , Settings and Bridge Pairings. So one should not interfere with another in the future.

**Comment by Hyrules** [comment]
Can you try the version in #108 and let me know if you still have this problem ? Thanks.

**Comment by Hyrules** [comment]
fixed in RC4
