### ISSUE TITLE
colour loop

### ISSUE THREAD

**Issue by D1311** [Hyrules/WinHue3#118]
I was hoping I could put this in Schedule/Timer/Alarm.

**Comment by Hyrules** [comment]
can you try the version in #108 and let me know if this is still happening for the crash ? For the color loop i will see what I can do.

**Comment by Hyrules** [comment]
Color loop has been implemented in the schedule. Let me know if this doesn't work.

**Comment by Hyrules** [comment]
this I can reproduce. I have to rework the code for the schedules anyway. I just discovered that you can actually schedule an operation on a sensor...

**Comment by Hyrules** [comment]
This should work in the latest version let mw know if this does not work.

**Comment by D1311** [comment]
Where do I find it.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Hyrules** [comment]
Release page : https://github.com/Hyrules/WinHue3/releases

**Comment by Hyrules** [comment]
hmmm... does bother trying it. It seem for some reason it does not work. Gonna fix this now.

**Comment by Hyrules** [comment]
Use the propertygrid instead. It will work. The sliders doesn't.

**Comment by Hyrules** [comment]
Ok I have fixed it just redownload the lastest release again and it will work.

**Comment by D1311** [comment]
Job done, working

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
