### ISSUE TITLE
"Pairing complete" message truncated

### ISSUE THREAD

**Issue by Naharis** [Hyrules/WinHue3#12]
![winhue-20160825](https://cloud.githubusercontent.com/assets/9617215/17967455/90850e12-6ac7-11e6-8ac4-f0ad66026223.png)

**Comment by Hyrules** [comment]
Thanks for the report. I will correct this.

**Comment by Hyrules** [comment]
This should be fixed in the next version. I'll try to upload a new version soon. I'm still catching some bugs related to the rewrite of HueLib.

**Comment by Hyrules** [comment]
can you tell me if this is fixed for you in the latest version ?
