### ISSUE TITLE
Please add a setting to minimize to tray

### ISSUE THREAD

**Issue by CherryLax** [Hyrules/WinHue3#120]
If I open the program after the startup process I cannot minimize into the tray. I would like to see this as an option in the future so that the window doesn't show up in the taskbar as it normally does

**Comment by Hyrules** [comment]
Will do so in the next version.

**Comment by Hyrules** [comment]
After looking into this the Notify Icon is already there. You just cannot minimize to tray from the main window adding a minimize to tray button with the title bar button is almost impossible in C#. You can send the app to tray by double clicking the icon in the tray bar.

**Comment by Hyrules** [comment]
Added to the latest release.
