### ISSUE TITLE
unexpected error - resulting in shut dowm.

### ISSUE THREAD

**Issue by Hoekeren** [Hyrules/WinHue3#124]
When i try to edit a schedule WinHue3 report an unexpected error and shuts down. 

How do I upload the eventlog?

Hope you can resolve my issue. 

Regards Christian

**Comment by Hyrules** [comment]
You just have to drag and drop the file in the box here where you type.

**Comment by Hoekeren** [comment]
When pressing the eventlog icon, the eventlog opens i a new windows. Is there anywhere else to look for the file?
![image](https://user-images.githubusercontent.com/33251946/32335347-f1f5fafa-bfec-11e7-80ce-ebcc8e6a0e43.png)

![image](https://user-images.githubusercontent.com/33251946/32335391-115854f6-bfed-11e7-8768-f0e936e97aac.png)

**Comment by Hyrules** [comment]
I need the full log with the error in it. The log is in your appdata folder in your user account in Windows. In Windows explorer in the bar type %appdata%\WinHue\log it should send you inside the log folder directly.

**Comment by Hoekeren** [comment]
[log 2017-01-31.txt](https://github.com/Hyrules/WinHue3/files/1440511/log.2017-01-31.txt)

**Comment by Hyrules** [comment]
you are using an old version of WinHue. Please update to the latest version if WinHue and let me know if the error is still happening.

**Comment by Hoekeren** [comment]
unistllalled and reinstalled using the installer. Same error message?

[WinHue3 2017-11-03.txt](https://github.com/Hyrules/WinHue3/files/1441185/WinHue3.2017-11-03.txt)

**Comment by Hyrules** [comment]
ok I have found which schedule causes the crash. I'll see I can do about it.

**Comment by Hyrules** [comment]
Yeah basically the schedule system does not support operations on a sensor at the moment so that's why you are having a crash. The Philips hue api is not really friendly and most of the error I get here is because of something not expected from the hue api. I will fix the error for the time being but I will not implement this right away. It's rather complex and I might have to redo the whole scheduling system.

**Comment by Hyrules** [comment]
You can try this version. You will not be able to modify a schedule which has a sensor as command.

[WinHue 3 RC 3 - 3.0.314.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1442398/WinHue.3.RC.3.-.3.0.314.0.Setup.zip)

**Comment by Hoekeren** [comment]
Thanx for the very swift responce.

**Comment by Hyrules** [comment]
This behavior should work in the latest release. Let mw know if this does not.
