### ISSUE TITLE
Command line parameters

### ISSUE THREAD

**Issue by wally007** [Hyrules/WinHue3#125]
Hello,

I'm trying to get command line parameters working however relative values ( + or - ) are not working.
Is there any other way to increase or decrease brightness/hue/saturation via command line ?

For example this works (sets the absolute brightness of a group to 50):
`whc.exe -g=1 --bri="50"`

but this doesnt (goal is to increase its current brightness value by 50)
`whc.exe" -g=1 --bri="+50"`

I want to add "increase" and "decrease" scripts to some of my remote buttons. 
Thanks.

**Comment by Hyrules** [comment]
Honestly I have not tested whc in a while. There might be bug in the program since the latest modification normally you are not supposed to use quotes when specifying values. I will eventually have to separate whc from WinHue in order to prevent those kind of problem.  I'll try to see if there is a bug here.

**Comment by wally007** [comment]
Thanks. It's the same with or without quotes (ie. absolute values work , relative dont)

**Comment by Hyrules** [comment]
lol actually after rereading your message I think I was lost a little the day I replied. You cannot actually use a negative number on any value. You would have to use the _inc values which are not implemented at the moment.

**Comment by Hyrules** [comment]
Here. Try this version the incrementors are now implemented in WHC. you have to use bri_inc etc...

[WinHue 3 RC 4 - 3.0.317.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1451963/WinHue.3.RC.4.-.3.0.317.0.Setup.zip)

**Comment by Hyrules** [comment]
actually this only work for the lights at the moment. I will add the groups asap.

**Comment by Hyrules** [comment]
This version should work with groups as well.

[WinHue 3 RC 4 - 3.0.319.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1452078/WinHue.3.RC.4.-.3.0.319.0.Setup.zip)

**Comment by wally007** [comment]
Thanks, I will give it a shot this weekend.-vlad

**Comment by Hyrules** [comment]
Verdict ? working ?

**Comment by wally007** [comment]
hello, yes its working as expected.
Thanks a lot !

**Comment by Hyrules** [comment]
Available in RC5
