### ISSUE TITLE
How to start scenes with CLI

### ISSUE THREAD

**Issue by jnk22** [Hyrules/WinHue3#126]
Hey there, first of all, thanks for this great tool!

I have been trying to set up a few shortcuts for my keyboard, unfortunately I don't know how to start any scenes from the command line and the wiki doesn't really help there, either :/

These shortcuts are working already:
- **Lights on:** "C:/Program Files (x86)/WinHue 3/whc.exe" -g=1 --on=true --bri=255
- **Lights off:** "C:/Program Files (x86)/WinHue 3/whc.exe" -g=1 --on=false

I have a few default scenes for my Philips Hue lights, eg. "Lesen", "Nachtlicht" and so on.

I have tried the following:
- "C:/Program Files (x86)/WinHue 3/whc.exe" --scene=Nachtlicht
- "C:/Program Files (x86)/WinHue 3/whc.exe" --scene="Nachtlicht"
- "C:/Program Files (x86)/WinHue 3/whc.exe" --scene="Nachtlicht.scn"
- "C:/Program Files (x86)/WinHue 3/whc.exe" -g=1 --scene=Nachtlicht
- "C:/Program Files (x86)/WinHue 3/whc.exe" -g=1 --scene="Nachtlicht"
- "C:/Program Files (x86)/WinHue 3/whc.exe" -g=1 --scene="Nachtlicht.scn"

None of those work.. Do I have to save any scene files somewhere before?

Thank you!

**Comment by Hyrules** [comment]
you have to use the ID of the scene not the name.

**Comment by jnk22** [comment]
That worked, thanks a lot! 👍
