### ISSUE TITLE
Website Redesign

### ISSUE THREAD

**Issue by banksio** [Hyrules/WinHue3#129]
I've been thinking about the WinHue website for a while and whilst the application itself has progressed loads, I think the webpage has kind of been left behind - it's not at all bad, but I think it doesn't represent the polish of WinHue in its current state.

So, I've mocked-up a redesign of the Webpage! You can demo it on [my fork](https://banksio.github.io/WinHue3/), but there's a few things left to do:
- Add donate buttons.
- Finishing touches as there are a few bugs needing to be ironed out.

I hope you like it, and if there's anything you'd like changed let me know!

**Comment by Hyrules** [comment]
Wow nice ! If you want to make a commit to the web page branch you are welcome !

**Comment by D1311** [comment]
Very nice.

**Comment by banksio** [comment]
Thanks!! I will finish it off in this next week and pull request. In the meantime, is there anything you'd like me to change?

**Comment by D1311** [comment]
If you watch it changes colour (I always like my colour loop).

**Comment by Hyrules** [comment]
It's perfect as it is for me. I really like the color rotation of the header.

**Comment by banksio** [comment]
Cool, yeah I'll finish it off in the week and see how it goes!

**Comment by Hyrules** [comment]
if you are good with css, html and javascript I might have something else for you if you feel like it. If you go in my profile you will see that I have created a new repo for something I'm working on for fun which is actually written with HTML, CSS and VueJS. Visual design is not my forté. It's very bland at the time. But it might become something more pleasant visually and an alternative to WinHue.

**Comment by banksio** [comment]
@Hyrules Very interesting as I've tried to make my own web based hue control panel before - as you can probably imagine it looks nice but doesn't actually work ☺️ I'm somewhat new to CSS and web design too but getting the hang of it. Will fork and take a look soon.
