### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by neiljt** [Hyrules/WinHue3#131]
When attempting to pair bridge with app, log below.
platform: windows 10 x64, all updates to date.
[WinHue3 2017-11-24.txt](https://github.com/Hyrules/WinHue3/files/1502628/WinHue3.2017-11-24.txt)

**Comment by Hyrules** [comment]
Please try RC3 and let met know if this still occures.

**Comment by neiljt** [comment]
hello.
installed rc3, wasn't aware that it was ready. problem solved
thank you.
all the best.
neil

**Comment by Hyrules** [comment]
Np problem. Glad to here your issue is fixed. Closing this now.
