### ISSUE TITLE
toggle on / off to dimmed

### ISSUE THREAD

**Issue by kiterway** [Hyrules/WinHue3#133]
Problem:  Want to turn on the light without waking up spouse... the bottom panel is one way but not the most user friendly say for my kids or my spouse.

Ad a toggle switch to the control panel such that one can easily turn on / off a light rather than double click AND more importantly the toggle goes to prior state (dimmed, color etc).  

Another approach would be to allow the controls (ie dimmer) to be dual purpose.  For example one could using the dimmer control (right window pane) to actually turn on the light immediately to the selected amount of dimming.

As it stands one must 1st double click the light which goes to 100% brightness (or use the "scenes" buttons which aren't obvious to wife, kids, grandparents, etc.)

**Comment by Hyrules** [comment]
I will see what I can do about this.

**Comment by Hyrules** [comment]
I was looking at the app and there is actually a way to do this. You can set by default the brightness of the bulb by going in the app settings and the default tab. This is a temporary way of doing it and will apply to all bulbs and groups.

**Comment by Hyrules** [comment]
Implemented in RC4 let met know if this does not do it for you.
