### ISSUE TITLE
Unhandled Exception: Winhue 3 during Pairing

### ISSUE THREAD

**Issue by wo-rasp** [Hyrules/WinHue3#135]
I have a Gen 2 Bridge and until yesterday was using WinHue3 for WP8.1 and W10 and had a setup with my own scenes to integrate Hue dimmers. I got two Livingcolors Bloom (LCT005, Gen 3) lamps. I found a HowTo for integrating them using iOS apps (Did not realize that WinHue3 is also supporting the TouchLink feature).
In brief my bridge crashed while adding the remote controller (round shaped one with 3 AAA batteries) to the bridge. After that i had to reset the bridge, lost all config data and restarted from scratch. I had to use my Hue Dimmer to reset all my lamps - the bridge did not detect anything anymore. I used the Philips iOS app to rebuild the environment.

Trying to pair the bridge with Winhue 3 triggers an Unhandled Exception.
[WinHue3 2017-12-04.txt](https://github.com/Hyrules/WinHue3/files/1528010/WinHue3.2017-12-04.txt)

**Comment by Hyrules** [comment]
I will take a look asap.

**Comment by GrimDeclaw** [comment]
Hi,
I tried something similar yesterday, and face the exact same issue (bulb reseting, bridge reseting and rebuilding everything) and faced the same WinHue crash.
To solve it, just delete the C:\User\UserName\AppData\Roaming\WinHue\WinHueBridges.set file and you'd be able to pair it again
