### ISSUE TITLE
Hotkeys do not save

### ISSUE THREAD

**Issue by foxotic** [Hyrules/WinHue3#136]
I have had to set this up 3 times and it's still happening.

Will click DONE several times just to make sure its still there. But as soon as the application is closed out, every hotkey i setup is gone. 
There is no save button i can find anywhere, so unless I'm missing something besides just hitting DONE, This has the be a bug. Please fix this asap

**Comment by Hyrules** [comment]
THis will be fixed in the next version. Meanwhile your can try the version in #132 .

**Comment by foxotic** [comment]
How do you get a legacy version?

**Comment by Hyrules** [comment]
Take the release you want in the release page : https://github.com/Hyrules/WinHue3/releases but you might encounter some bugs in it.

**Comment by foxotic** [comment]
Sorry I'm new to github and how it works. How do i know which is #132 ? also what's an ETA for the next published release?

Side note - why not just hotfix known patches if you have them ready?

**Comment by Hyrules** [comment]
it is not possible to hotfix in C#. It's a compiled language. I have to recompile everytime and make an installed so the users can install on their pc. You can try this version and let me know if this is fixed. Also there is a bug with the propertygrid. In this version it does not clear itself. I'm starting to believe that the programmer of the WPF toolkit are making this on purpose so the can get people to buy the support and have the latest fixed version. Problem is that there is no other property grid.

[WinHue 3 RC 4 - 3.0.995.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1564943/WinHue.3.RC.4.-.3.0.995.0.Setup.zip)

**Comment by Hyrules** [comment]
Fixed in RC4 let me know if you still have this issue.
