### ISSUE TITLE
Not an issue, more a feature suggestion : "Power cut set of rules"

### ISSUE THREAD

**Issue by GrimDeclaw** [Hyrules/WinHue3#138]
One thing that was bothering me with the hue system is the fact that after a power cut, all the lights would turn on, and stays that way.

After some search, I found a 1 rule, 1 timer and 2 sensors "kind of solution".
I thought it would be a nice feature on WinHue to have a "Powercut Light off" button that would create those items.

Here is the json for this 4 items (while the timer and the rule must be adjusted to use created sensors id):

The 2 sensors are simple CLIPGenericStatus:

This is the id 8 sensor
```
{
  "name": "PCStateSensor",
  "modelid": "ipsensor",
  "swversion": "1.0",
  "type": "CLIPGenericStatus",
  "manufacturername": "statesensor_pc",
  "uniqueid": "statesensor_pc",
  "config": {
    "on": true
  }
}
```

This is the id 9 sensor
```
{
  "name": "PCInitSensor",
  "modelid": "ipsensor",
  "swversion": "1.0",
  "type": "CLIPGenericStatus",
  "manufacturername": "initsensor_pc",
  "uniqueid": "initsensor_pc",
  "config": {
    "on": true
  }
}
```

The timer is a 10 seconds repeating timer, which set the id 8 sensor status to 1:
```
{
  "name": "PCHeartbeat",
  "localtime": "R/PT00:00:10",
  "description": "Powercut Heartbeat",
  "command": {
    "method": "PUT",
    "address": "/sensors/8/state",
    "body": {"status":1}
  },
  "status": "enabled",
  "recycle": false
}
```

Finally the rule is simple : on sensor 8 dx, if sensor 9 value is 0, set it to 1 and turn off groups/0 lights (ie all lights).
This works because on bridge init, all sensors state are set to 0, so after boot the lights will go off and the sensor 9 will be set to 1, which will prevent the all lights off  "PCRule" rule to trigger

```
{
  "name": "PCRule",
  "conditions": [{"address":"/sensors/8/state/lastupdated","operator":"dx"},{"address":"/sensors/9/state/status","operator":"eq","value":"0"}],
  "actions": [{"address":"/sensors/9/state","method":"PUT","body":{"status":1}},{"address":"/groups/0/action","method":"PUT","body":{"on":false}}],
  "status": "enabled"
}
```

Don't know if someone else will find it usefull, but as far as I'm concerned I'm much confident leaving my house with those set!

**Comment by Hyrules** [comment]
I'm curious as wether this really works or not. Since Philips Hue bulbs does not remember their previous state when turn off this will most likely result in a brief flash on power resume or the bulb will stay on as long as the bridge has not booted up. It's better than nothing but if you want my input on this install LIFX bulb where this matters. They recall their state on powerloss.

**Comment by GrimDeclaw** [comment]
Yes, the bulb stays on until the bridge has finished booting, but at least they then turn off when the timer trigger the rule.
Without this, the bulb just stays on until you come back home... hard if it happens 5mn after your departure for work in the morning!

**Comment by Hyrules** [comment]
This feature request is not useful anymore. Philips has finally implemented this functions in their bulbs.
