### ISSUE TITLE
BUG Hotkeys

### ISSUE THREAD

**Issue by thowtue** [Hyrules/WinHue3#139]
Bonjour, je vois que tu parles français je vais donc m'épargner la peine de la faire en anglais !

D'abord merci beaucoup pour le travail fait sur ton application, ça m'est très utile pour pouvoir appliquer des raccourcis clavier à mes presets !

Alors, j'ai actuellement trois problèmes,
1/ Dans les options, le lancement "Minimized" et "Tray" sont inversés, quand je règle sur tray il me lance l'app en minimized et inversement.

2/ Je règle donc le lancement sur le sytem tray (avec l'option minimized du coup) mais quand l'app se lance dans le sytem tray je n'ai aucun raccourci clavier qui fonctionne. je dois double cliquer sur l'icône du tray pour que l'app se restore et charge, ensuite seulement les raccourcis fonctionnent.
A savoir qu'en lançant l'app en minimized il n'y a pas ce problème !

3/ La combinaison de touches "Alt + [key]" ne fonctionne pas. Lorsque je combine Alt avec n'importe quelle autre touche, il m'écrit "Alt + System".

D'avance merci de ta réponse :)

**Comment by Hyrules** [comment]
Pour 1 et 2, je vais corriger le problème. Pour le #3 si tu veux essayer la version dans le topic #136 au bas de la page je sais qu'il y a un bug avec la dernière version du WinHue et les hotkeys sinon je vais corriger le problème dès que possible.

**Comment by thowtue** [comment]
Je viens de tester la build 1020 et le problème est toujours présent pour la combinaison de touches "Alt + [key]"

Merci de ta réponse rapide !

**Comment by Hyrules** [comment]
Effectivement 3 je peux reproduire le bug ici. Je vais corriger ça.

**Comment by thowtue** [comment]
Merci !

**Comment by thowtue** [comment]
Est-ce qu'il serait aussi possible de rajouter une option qui ferait en sorte que quand on ferme l'application elle aille dans le system tray plutôt que de se fermer complètement ?
Merci d'avance :)

**Comment by Hyrules** [comment]
Dans la nouvelle version j'ai ajouter un bouton qui permet de minimizer vers le tray dans la barre de menu à coté du bouton minimizer. Tu peux essayer cette version elle corrige les bugs rapportés.

[WinHue 3 RC 4 - 3.0.1153.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1580908/WinHue.3.RC.4.-.3.0.1153.0.Setup.zip)

**Comment by thowtue** [comment]
Merci, je viens de tester, et je ne peux plus créer de hotkeys, j'ai d'abord voulu essayer mes raccourcis mais j'ai vu qu'ils ne fonctionnaient pas, j'ai voulu modifier mais quand je clique sur une des hotkeyx l'application plante. J'ai donc wipe les données dans appdata je me suis reco à mon bridge et j'ai voulu remettre de nouveaux hotkeys mais après avoir sélectionné dans le menu déroulant "scenes" le menu d'après ne me propose rien du tout, et pareil si je met lights ou groups. Du coup je ne peux pas tester savoir si les raccourcis fonctionnent au démarrage de l'application dans le system tray.
De plus je viens d'essayer deux fois, l'appli ne démarre pas du tout au démarrage de windows, pourtant elle est bien au démarrage quand je vérifie dans "msconfig" ou dans le gestionnaire des tâches vu que je suis sur win10.

mon dernier log log est là:
[WinHue3 2017-12-22.txt](https://github.com/Hyrules/WinHue3/files/1580971/WinHue3.2017-12-22.txt)

**Comment by Hyrules** [comment]
hmm ok je viens de reproduire le crash je regarde ça dans quelques minutes et je te reviens.

**Comment by thowtue** [comment]
ça marche, merci !

**Comment by Hyrules** [comment]
Voici laisse moi savoir si ça fonctionne.

[WinHue 3 RC 4 - 3.0.1165.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1581128/WinHue.3.RC.4.-.3.0.1165.0.Setup.zip)

**Comment by thowtue** [comment]
Alors pour le mappage des raccourcis c'est bon, ça refonctionne, par contre au démarrage il ne se lance toujours pas, et de plus si je lance manuellement, avec l'option dans le system tray, je n'ai toujours pas les contrôles sur les raccourcis tant que je n'ouvre pas la fenêtre complètement malheureusement

**Comment by Hyrules** [comment]
ok je vais voir pour le démarrage j'ai manqué ce bout la.

**Comment by thowtue** [comment]
Pas de soucis !

**Comment by Hyrules** [comment]
3iem prise... celle-la devrait être la bonne.

Ca devrait corriger le bug des hotkey non disponible au démarrage (testé) et du démarrage automatique(non testé)

[WinHue 3 RC 4 - 3.0.1182.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1581204/WinHue.3.RC.4.-.3.0.1182.0.Setup.zip)

**Comment by thowtue** [comment]
Je confirme ça fonctionne bien quand on démarre l'app dans le système tray !
Par contre au démarrage de windows l'appli ne se lance toujours pas

**Comment by Hyrules** [comment]
Tu est capable d'aller dans le registre de windows ?

Ici : HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run

tu devrais avoir une clé WinHue 3 avec le path vers l'exe.

**Comment by thowtue** [comment]
Yes, je check

**Comment by thowtue** [comment]
J'ai ça, et c'est bien le bon chemin, par contre y'a pas d'arguments à la fin, je sais pas si ça peut jouer, mes autres apps ont des arguments pour certaines et le chemin est entre "", je sais pas si je peux essayer de juste rajouter les "" pour voir si ça marche...

![image](https://user-images.githubusercontent.com/34699555/34282156-bd266d5c-e6c3-11e7-933a-7717a175360d.png)

**Comment by Hyrules** [comment]
oui faudrait que tu resauvegarde tes settings dans le menu des settings ça va ajouter les "". c'est probablement pour ça que ca fonctionne pas.

**Comment by thowtue** [comment]
Ah, oui possible, je test et je te dis.

**Comment by thowtue** [comment]
Non ça ne fonctionne toujours pas de mon côté

**Comment by Hyrules** [comment]
les guillemets sont la maintenant ?

**Comment by thowtue** [comment]
Oui, ça c'est bon

**Comment by Hyrules** [comment]
hmmm ok je vais continuer à esayer de trouver pourquoi ça veut pas ouvrir au démarrage demain.

**Comment by thowtue** [comment]
Ok, très bien !

**Comment by Hyrules** [comment]
Nouvelle version à tester cette version créee un raccourci dans le menu Démarrage (startup) de windows au lieu de créer une clé de registre.

[WinHue 3 RC 4 - 3.0.1187.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1583028/WinHue.3.RC.4.-.3.0.1187.0.Setup.zip)

**Comment by thowtue** [comment]
Ah, je pensais justement que c'était le cas du coup, j'ai pas été vérifier, je test ça.

**Comment by thowtue** [comment]
Alors, ça ne fonctionne toujours pas, qui plus est ton installer n'a pas l'air de mettre le raccourcis dans mon dossier de démarrage, (j'ai été vérifier) j'en ai mis un manuellement, et ça ne fonctionne toujours pas, du coup j'ai tenté de virer le lancement en administrateur dans le raccourcis, et là ça se lance, mais l'application sort une erreur et plante (cf: log) j'ai remis en administrateur et ça ne se lance pas, je pense que le problème se situe à ce niveau, mais je ne sais pas pourquoi il refuserait de lancer l'app en administrateur.

[WinHue3 2017-12-22.txt](https://github.com/Hyrules/WinHue3/files/1583089/WinHue3.2017-12-22.txt)

**Comment by Hyrules** [comment]
ça prends le dossier de démarrage dans le raccourci sinon ça plante. Je vais continuer à voir pourquoi ça ça créer pas le raccourci.

![image](https://user-images.githubusercontent.com/3161577/34306698-88e87662-e712-11e7-9f06-41dca61e3bb8.png)

**Comment by thowtue** [comment]
Pourtant, j'avais bien fait gaffe d'y mettre l'emplacement

![image](https://user-images.githubusercontent.com/34699555/34306854-9d2fa9e6-e745-11e7-8c04-c72bcdbbb715.png)

**Comment by Hyrules** [comment]
si tu regarde le log il semble chercher pour le dossier lights dans Windows system32 ce qui cause le crash.
ystem.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\WINDOWS\system32\lights' je vais tenter quelque chose...

**Comment by thowtue** [comment]
Apparemment ce serait le chemin qui est en absolu, dans un de tes fichiers il doit y avoir le chemin qui doit partir du raccourcis et pas du .exe quelque chose comme ça

**Comment by Hyrules** [comment]
je vais tenter de modifier le code qui vérifie le chemin mais j'ai pas hard codé le chemin. Il est supposé prendre le path du exe.

**Comment by Hyrules** [comment]
Si tu as encore le raccourci dans le menu démarrer enleve le et refaire le save settings. Ensuite essaie de démarrer le raccourci pour voir si ça fonctionne. Après si le raccourci fonctionne tu peux essayer le startup.

[WinHue 3 RC 4 - 3.0.1190.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1583128/WinHue.3.RC.4.-.3.0.1190.0.Setup.zip)

**Comment by thowtue** [comment]
J'ai déjà eu un problème à ce niveau mais c'était pour un simple script, j'avais dû aller chercher d'abord la console dans system32 et ensuite entrer mon chemin en relatif, tout ça dans le champs de la cible.

Je test tout ça, et je te dis !

**Comment by thowtue** [comment]
Alors, le raccourcis fonctionne bien, cependant au startup j'ai toujours le plantage (log).
J'ai aussi remarqué que l'application se lançait 2x une des deux plante, et l'autre se lance sans erreur 
mais ne fait pas fonctionner les raccourcis, même après avoir ouvert l'application.

[WinHue3 2017-12-22.txt](https://github.com/Hyrules/WinHue3/files/1583149/WinHue3.2017-12-22.txt)

**Comment by thowtue** [comment]
Est-ce normal que dans le log j'ai un path qui provient de tes fichiers ?
"D:\\Documents\\Visual Studio 2015\\Projects\\WinHue3\\WinHue3\\Utils\\"
Il y en a d'autres de chemins comme ça.

**Comment by Hyrules** [comment]
non ca devrait pas... bizarre je vais regarder le log.

**Comment by Hyrules** [comment]
Le crash est  encore générer par le path qui est pas bon...

**Comment by thowtue** [comment]
Oui, mais tu risques de devoir fouiller tout ton code pour voir/modifier tous les chemins, non ?

**Comment by Hyrules** [comment]
non ces codes la sont généré par le système de log. C'est pas ces chemins la qui sont pas bon. C'est vraiment le path vers le dossier des images des lumières je vais regarder si je trouve pas quelques chose à propos de raccourcis.

**Comment by thowtue** [comment]
D'accord, je sais que j'avais galéré de mon côté pour faire fonctionner mon raccourcis avec mes dépendances et j'ai pu uniquement le mettre dans le dossier parent des dépendances, sauf si je modifiais dans le raccourcis le chemin en conséquences

**Comment by Hyrules** [comment]
euh ? je suis pas certain de comprendre ce que tu essai de faire ici avec le batch file. Si tu roule WinHue et que tu le met en mode start in tray par exemple. Il te crée un raccourci dans le dossier Démarrage ? et si tu clique sur ce raccouri est-ce que l'application démarre bien ? De mon coté ça fonctionne en ce moment.

**Comment by thowtue** [comment]
L'histoire du batch c'est un truc que j'avais fais il y a un certain temps c'est pas en rapport avec ton app lol, c'était juste histoire de te donner un exemple sur le fait que le chemin était en relatif selon le dossier.
Sinon oui le raccourci fonctionne bien en le lançant depuis le dossier de démarrage, mais au startup, j'ai cette erreur qui revient et aussi comme je t'ai dit, l'app qui démarre deux fois apparemment.

**Comment by Hyrules** [comment]
Ok le bug du demarrage en double je suis pret a miser sur l'entrée de registre qui reste de l'ancienne méthode . Tu peux la supprimer et ressayer?

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run

**Comment by thowtue** [comment]
Je la vire et je te dis !

**Comment by thowtue** [comment]
C'est tout bon ! Je te remercie !

**Comment by Hyrules** [comment]
Super hésite pas si ya autre choses.

**Comment by thowtue** [comment]
ça marche ! En tout cas super réactivité de ta part, c'est vraiment cool, je t'ai fait un petit don tu le mérites :)

**Comment by Hyrules** [comment]
Merci!  j'essaie d'aider comme je peux.

**Comment by thowtue** [comment]
Et tu aides bien!

**Comment by Hyrules** [comment]
C'est pratique quand la personne qui demande de l'aide reste pour avoir du support et faire des tests. Souvent les gens restent pas et se poussent rapidement. Si tu as des idées ou suggestions je suis ouvert.

**Comment by thowtue** [comment]
C'est normal après tout, c'est moi qui ai un besoin, si je demande de l'aide, je vais pas me barrer, ce serait idiot, ça résoudrait pas mon problème !
j'ai bien une suggestion, mais c'est je pense quelque chose d'assez compliqué.
Je veux bien expliquer mais je sais pas si le faire à la suite dans ce thread c'est judicieux, à toi de me dire !

**Comment by Hyrules** [comment]
Je vais fermer ce thread comme résolue tu peux en ouvrir un autre que je mettrai comme feature request.

**Comment by thowtue** [comment]
ça marche
