### ISSUE TITLE
Modification d'une règle impossible

### ISSUE THREAD

**Issue by OUARZA** [Hyrules/WinHue3#144]
Bonjour,
Depuis la dernière version, je ne peux plus modifier les règles.

Pouvez-vous m'aider ?
Merci
![philips hue2](https://user-images.githubusercontent.com/34892335/34386364-908f0394-eb28-11e7-8bcd-cc1a84ec1edb.JPG)

**Comment by Hyrules** [comment]
Svp m'envoyer une copie du journal ici en fichier txt je vais voir si c'est un bug. Merci. Le fichier log se trouve dans le dossier log de WinHue dans le dossier appdata de l'utilisateur -> %appdata%\WinHue coller ceci dans Windows explorer pour aller directement dans le dossier.

**Comment by OUARZA** [comment]
Pas de données personnelles dans ce fichier ?
[WinHue3 2017-12-27.txt](https://github.com/Hyrules/WinHue3/files/1589515/WinHue3.2017-12-27.txt)

**Comment by Hyrules** [comment]
Rien de personnelles qui peut t'identifier personnellement. Je vais l'enlever dans quelques secondes.

**Comment by OUARZA** [comment]
ça marche, merci :)

**Comment by Hyrules** [comment]
en fait c'est 500 x 10 qui est 5 secondes mais je vais vérifier. C'est normal pour la version 311 parce que j'ai complètement modifié le créateur de règle. Il se peut qu'il y ait des bugs. Je fais pas de tests exhaustifs des modules. Je n'ai malheureusement pas toutes les capteurs et règles possible. Comme l'API de Philips est très peu documenté ou mal documenté.

**Comment by OUARZA** [comment]
Dans l'api transitiontime, on met la valeur en ms, ce qui prête à confusion ;)
Si besoin, je peux tester l'application.

**Comment by Hyrules** [comment]
correction : 

transitiontime | uint16 | 

The duration of the transition from the light’s current state to the new state. This is given as a multiple of 100ms and defaults to 4 (400ms). For example, setting transitiontime:10 will make the transition last 1 second.

multiple de 100 au lieu de 10 donc par défaut c'est 4 qui représente 400ms. donc pas de multiplication dans WinHue. Le bridge le fait lui même. Il prends un entier que j'envoi.

**Comment by Hyrules** [comment]
ah he c'est effectivement un bug.

**Comment by OUARZA** [comment]
Ok. N'hésites pas si il faut tester la RC5

**Comment by Hyrules** [comment]
oui je vais corriger le bug et mettre une version que tu pourras tester ici.

**Comment by Hyrules** [comment]
Voici : 

[WinHue 3 RC 5 - 3.0.1395.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1590048/WinHue.3.RC.5.-.3.0.1395.0.Setup.zip)

**Comment by OUARZA** [comment]
Parfait, plus d'erreur ;)

**Comment by Hyrules** [comment]
super ! Je laisse le post la au cas ou d'autres personnes auraient le même bug sinon je vais poster une nouvelle version ce soir.
