### ISSUE TITLE
Antivirus Detection

### ISSUE THREAD

**Issue by AZ-Geek** [Hyrules/WinHue3#145]
When I attempt to use the option to check for WinHue update at startup, Windows Defender 10 is reporting a threat "Trojan:Win32/Fuerboos.C!cl". Very likely a false positive, however I suggest that you submit it to Microsoft for analysis. If MS can report back that it is clean then may be they will update their definitions.

**Comment by Hyrules** [comment]
Which version are you using ? I can assure you that there is no virus in WinHue. I compile the code myself and it's open source so you can see the code for yourself. Like you said it is most likely a false positive. I'm seeing many reports of false positive on the web from windows defender. What surprise me is that I didn't see this myself as I use Windows defender on my own pc that i'm developing on.

**Comment by AZ-Geek** [comment]
I was on 3.0.311.0 before I manually upgraded. I was simply letting you know that MS is flagging it as a threat. If enough developers submit their app/code to them for analysis, MS will eventually change their definition files.

**Comment by Hyrules** [comment]
Thanks for the info. I'll see what I can do about submitting my app to microsoft for analysis but the code can change so rapidly and often that I'm not sure that it would help at this point.

**Comment by Hyrules** [comment]
Tell me if you still have this issue with the latest version. I have completely changed the way the start with windows works. So this might not trigger a false positive anymore.

**Comment by Hyrules** [comment]
The behavior of WinHue has been changed so it should not trigger antiviruses anymore.
