### ISSUE TITLE
Modification d'une valeur de compteur impossible

### ISSUE THREAD

**Issue by Zen-45** [Hyrules/WinHue3#146]
Bonjour,

Je souhaitais ajouter une règle supplémentaire sur le bouton "on", mais je ne peux pas modifier la valeur du compteur qui permet de savoir à quelle N° de règle on est (aussi bien dans les conditions que dans les actions).
J'ai l'erreur suivante quand je clique sur "add" : 
![rule_state](https://user-images.githubusercontent.com/35011325/34470985-4185ba68-ef3d-11e7-9d37-616f05f82a3f.PNG)

Rq : J'ai installé la RC5 car j'avais le même pb que pour #144 .

Demande d'évolution : ajouter la possibilité de changer l'ordre des actions (sans avoir à les supprimer / recréer).

Cordialement

**Comment by Hyrules** [comment]
Oui effectivement je vois le problème je vais corriger et sortir une version fix sous peu.

**Comment by Hyrules** [comment]
Voici un version qui devrait corriger le problème et qui implémente le up and down dans les actions.

[WinHue 3 RC 5 - 3.0.1408.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1596592/WinHue.3.RC.5.-.3.0.1408.0.Setup.zip)

**Comment by Zen-45** [comment]
Super, merci pour votre retour rapide.
Je confirme que le correctif fonctionne et que le changement d'ordre des actions est opérationnel.

**Comment by Hyrules** [comment]
Super merci du feedback. Je vais faire un release fix pour cette version.
