### ISSUE TITLE
Keybinding

### ISSUE THREAD

**Issue by BadMan1981** [Hyrules/WinHue3#147]
Hey there. This looks like the powerful app i searched for but i am to dumb to use it.. Wanted to create seperate keybindings for flashing light in specific colours par example, but without documentation it just drives me crazy :D

**Comment by Hyrules** [comment]
Sorry for the delay. You need to create a hotkey. You can se the light to identify and set the hue to red this should do it.

**Comment by Hyrules** [comment]
If you still want help just reopen the issue otherwise i'm marking it as closed.
