### ISSUE TITLE
Bridge update broken?

### ISSUE THREAD

**Issue by LogicDeLuxe** [Hyrules/WinHue3#150]
"Check for bridge update" only shows me a grayed out "Update Firmware". When I uncheck "Check for Bridge version.", I can control, rename, group the lights etc., but I wasn't sure what would work and what not with API version 1.14 which was on my bridge.
I updated my Bridge manually with debug/clip.html following the procedure at https://www.developers.meethue.com/documentation/software-update
and successfully updated it to 1.22.0. Yet WinHue still says "Bridge update required" when "Check for Bridge version." is enabled.

**Comment by Hyrules** [comment]
The problem with the bridge update api is that i works until API version 1.16 I have not implented further updating for the newest bridge over that version because the API changes for the update. The old bridges does not get updates over 1.16. The newest goes over. Being backward compatible is a P.I.T.A.

**Comment by LogicDeLuxe** [comment]
So WinHue should have been able to update from API version 1.14, which mine had? It didn't.
And why is it still saying "Bridge update required" now that I'm on 1.22.0?

**Comment by Hyrules** [comment]
The label should indeed not be shown and yes you should have been able to update. I will take a look at this. It's been a while since I've wanted to rewrite the bridge update system.

**Comment by Hyrules** [comment]
Updating system has been updated to work with bridge version 1.20+ in the latest version. Let me know if this does not work.
