### ISSUE TITLE
"Controls" sliders enhancements

### ISSUE THREAD

**Issue by LogicDeLuxe** [Hyrules/WinHue3#151]
When a light is off, can you leave those sliders active instead of graying it out? Sometimes, you want to set some parameters before turning the light on. I know, the bridge doesn't accept changes when the light is off, but WinHue could just sent them together with the next on-command.
Also, would it be possible to have the transition time slider on a logarithmic scale and maybe mouse wheel support for fine adjustments?

**Comment by Hyrules** [comment]
Actually I was thinking of doing this eventually. I might implement this in the next version for the sliders. For the transition time slider, I still hesitating between a slider and a updown box with a value.

**Comment by Hyrules** [comment]
This has been added to the latest version. You have to change this behavior in the settings -> defaults -> sliders because it is not defaut. Marking this as closed.
