### ISSUE TITLE
"Bridge Settings" not editable

### ISSUE THREAD

**Issue by LogicDeLuxe** [Hyrules/WinHue3#153]
In the tabs "General Settings" and "Network Settings", The "APPLY" Button keeps grayed out, no matter what settings I change. In "Portal Status" and "Software Update Information", the checkboxes are not clickable, but can be toggled with the space bar. Also there is no "APPLY" button in those tabs at all.

**Comment by Hyrules** [comment]
Yep got this one. Correcting this. Thanks.

**Comment by Hyrules** [comment]
you can try the version in #155 this should be fixed in it.

**Comment by Hyrules** [comment]
This should be fixed in the latest version.
