### ISSUE TITLE
Hue slider background color is misaligned

### ISSUE THREAD

**Issue by LogicDeLuxe** [Hyrules/WinHue3#154]
The slider background does not match this table: https://www.developers.meethue.com/documentation/core-concepts#color_gets_more_complicated
For instance, when set near 46920, it should be dark blue. In fact, with full saturation my bulbs do shine dark blue there, but the hue slider is more like purple at that spot, and also the Saturation slider becomes purple.

**Comment by Hyrules** [comment]
I'll see what I can do to fix this. thanks.

**Comment by Hyrules** [comment]
I have adjusted the hue slider so it's more representative of the color. The offset seems to be better now thanks.

**Comment by Hyrules** [comment]
I will mark this issue as fixed. If you find that the alignment is still off don't hesitate to reopen it.
