### ISSUE TITLE
Unable to check for "effect" in rule

### ISSUE THREAD

**Issue by Juchar** [Hyrules/WinHue3#155]
If I want to check for `/lights/id/state/effect eq colorloop` in the rule editor and I press save I get the error:

> Type: 7, invalid value, colorloop, for parameter, value at adress /rules/3/conditions/2/value

Same happens when I try to check it for groups using `/groups/id/action/effect eq colorloop` whereas here I am not sure if you can check for actions at all (I am new to hue).

**Comment by Hyrules** [comment]
Thanks I will take a look at this asap.

**Comment by Hyrules** [comment]
Yes this was actually a bug. I corrected this in this version. Here you go. This version should work properly.

[WinHue 3.0.1565.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1617009/WinHue.3.0.1565.0.Setup.zip)

**Comment by Hyrules** [comment]
I will mark this as fixed. If you still have the issue don't hesitate to repopen it.
