### ISSUE TITLE
Can't edit group

### ISSUE THREAD

**Issue by nickelfault** [Hyrules/WinHue3#16]
When trying to edit a group, upon clicking the save button I receive the following error message:

![image](https://cloud.githubusercontent.com/assets/1516509/18210929/345980e6-70f8-11e6-8d0e-5df7643820f9.png)

**Comment by Hyrules** [comment]
Thanks for reporting this. I'll take a look asap.

**Comment by Hyrules** [comment]
This should be fixed in the next version. I'll try to upload a new version soon. I'm still catching some bugs related to the rewrite of HueLib.

**Comment by nickelfault** [comment]
Thank you! Patiently awaiting the new version :) Awesome app by the way!

**Comment by Hyrules** [comment]
take a look at issue #9 there is the latest version zipped. Try it and let me know if it works.

**Comment by nickelfault** [comment]
Funny, I was going to ask if you had any updates on this today :) Looks like it's working, thank you!
