### ISSUE TITLE
Feature request: Schedule as a rule action

### ISSUE THREAD

**Issue by LogicDeLuxe** [Hyrules/WinHue3#160]
I used to trigger a schedule with my dimmer switch. The bridge can do this just fine, but you can't select schedule in the rule's action menu.

**Comment by Hyrules** [comment]
Odd i will take a look at this might just be something I forgot to add when I redone rule creator.

**Comment by Hyrules** [comment]
Can you give me an example of a rule action that has a schedule in it ? you can do a copy as json of one you have and paste it here. It's trying to figure out how to do this. thanks.

**Comment by LogicDeLuxe** [comment]
`	"16": {
		"name": "tee4",
		"owner": "_key_",
		"created": "2018-01-09T21:59:09",
		"lasttriggered": "2018-02-04T12:54:06",
		"timestriggered": 18,
		"status": "enabled",
		"recycle": false,
		"conditions": [
			{
				"address": "/sensors/3/state/buttonevent",
				"operator": "eq",
				"value": "1002"
			},
			{
				"address": "/sensors/4/state/status",
				"operator": "eq",
				"value": "99"
			}
		],
		"actions": [
			{
				"address": "/groups/2/action",
				"method": "PUT",
				"body": {
					"alert": "select"
				}
			},
			{
				"address": "/schedules/4",
				"method": "PUT",
				"body": {
					"status": "enabled"
				}
			}
		]
	}`

**Comment by Hyrules** [comment]
thanks of I understand now you alter a schedule settings with the rule you do not trigger it.

**Comment by LogicDeLuxe** [comment]
Not sure what you mean by "trigger". PUTting { "status": "enabled" } does start the timer. In my case, that timer sends an { "alert": "select" } to a group after 4 minutes.
The timer can be aborted with { "status": "disabled" }

My schedule looks like this:`
"4": {
		"name": "Ziehzeit 4 Min.",
		"description": "",
		"command": {
			"address": "/api/_key_/groups/2/action",
			"body": {
				"alert": "select"
			},
			"method": "PUT"
		},
		"localtime": "PT00:04:00",
		"time": "PT00:04:00",
		"created": "2018-01-09T21:53:04",
		"status": "disabled",
		"autodelete": false,
		"starttime": "2018-02-06T21:40:09",
		"recycle": false
	}`

**Comment by Hyrules** [comment]
You don't actually trigger the schedule you just enable it. Since you enable it the timer starts and then trigger after 4 minutes then disable itself.

**Comment by Hyrules** [comment]
Her you can try this version and let me know what happens. It should be working.

[WinHue 3.0.1843.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1709200/WinHue.3.0.1843.0.Setup.zip)

**Comment by Hyrules** [comment]
Latest version should do what you ask. Let me know if this does do it.
