### ISSUE TITLE
bug: RC5 fix 2; Creating rule with dx comparator fails

### ISSUE THREAD

**Issue by Trenjeska** [Hyrules/WinHue3#162]
When creating a simple rule for a sensor that uses the sensors state/lastupdated value, you usually use a simple dx comparator without any value.
it now throws an exception from the bridge that 'value' cannot be "" (empty)
When tested and creating the rules using the CLIP debugger it does accept the json when the rule includes the sensor's state/lastupdate with dx, but only when there was no value property in the rule.

It seems the rule editor adds an empty value property to the json that is being created.

**Comment by Hyrules** [comment]
can you try the version in #160 and let me know if this is still occuring ? From looking at the code this has already been fix maybe just not published yet.

**Comment by Trenjeska** [comment]
I will try when I get the opportunity this weekend

**Comment by Trenjeska** [comment]
I tested the version from #160 and it indeed solves the dx rule creation
