### ISSUE TITLE
Theme is only applied after opening settings dialog

### ISSUE THREAD

**Issue by smklancher** [Hyrules/WinHue3#163]
If you change theme settings away from defaults (BaseLight, Cyan), then close and reopen, the theme will be back to default.  If you open the settings dialog, then the theme settings are applied.

This may be an obsolete issue if the theme might be redesigned per discussion in issue #148.  As also noted in that issue, the dark theme does not take effect on the ribbon.

**Comment by banksio** [comment]
Thanks - yes, the app is currently being redesigned so the styling will be overhauled too and this will be fixed then.

**Comment by smklancher** [comment]
Thanks!

**Comment by Hyrules** [comment]
Theming has been removed for now I will change this in the future.
