### ISSUE TITLE
Allow multiple conditions on the same sensor when creating a rule

### ISSUE THREAD

**Issue by torandi** [Hyrules/WinHue3#165]
When creating a rule, the program seems to disallow creating more than one condition per sensor ("Warning: A similar condition already exists, do you want to replace it", answering no does nothing).

I often find myself wanting to create a condition "When presence is true, and presence ddx 00:00:00" or similar, which I have to use the advanced tool for.

**Comment by Hyrules** [comment]
I'll take a look at this asap.

**Comment by torandi** [comment]
Thanks! The same seems to apply for actions. For example if I want to set two difference scenes.

**Comment by Hyrules** [comment]
This should fix both issue you reported. Let me know.

[WinHue 3.0.2135.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1778992/WinHue.3.0.2135.0.Setup.zip)

**Comment by torandi** [comment]
It does. Awesome!

**Comment by Hyrules** [comment]
thanks for the donation by the way and don't hesitate if you find anything else.
