### ISSUE TITLE
When Editing a rule: Condition/Action typ drop downs disabled sometimes

### ISSUE THREAD

**Issue by torandi** [Hyrules/WinHue3#167]
When editing an existing rule, the drop downs for Conditions/Actions sometimes get's disabled.
Repro:
* Edit an existing rule
* Select an item in the list to the right
* Try to change the dropdowns (to add a new item).

Expected result:
I can use the drop downs to create further conditions and rules 

Actual Result:
The drop downs are disable

**Comment by Hyrules** [comment]
Yes it a normal behavior in this case. Did you try to press the clear button ?
