### ISSUE TITLE
Feature Request: A quick and simple way to modify a GenericSensor

### ISSUE THREAD

**Issue by torandi** [Hyrules/WinHue3#168]
I find myself basic a lot of my logic around the GenericSensors (Flag & Status), and it would be nice to have a way to quickly change the values of the sensors from WinHue, to debug the logic, instead of having to write manual json.

**Comment by Hyrules** [comment]
This I can certainly do. Will try to implement it asap.

**Comment by Hyrules** [comment]
In the menu on top go to view and go to Toolbars. In toolbar check sensors. A new toolbar will appear that will allow you to set the status and the flag or the respective sensor. Let me know what you think.

[WinHue 3.0.2154.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1783060/WinHue.3.0.2154.0.Setup.zip)

**Comment by torandi** [comment]
Thanks this works well :)
