### ISSUE TITLE
Console bug saturation

### ISSUE THREAD

**Issue by ksbansal** [Hyrules/WinHue3#17]
For some reason which ever --sat value I enter in the console, it gets ignored. It always stays at 76.
Please fix.

**Comment by Hyrules** [comment]
can you try the version in issue #9 and let me know if the bug still occurs. There's been alot of changes to latest version.

**Comment by ksbansal** [comment]
still have the same issue. forgot to add that even if I remove -sat from the console command it changes it to 76.

**Comment by Hyrules** [comment]
can you give me exact command because i can't seem to be able to reproduce it here.
