### ISSUE TITLE
Hotkey Creator "Name" issue

### ISSUE THREAD

**Issue by pier13** [Hyrules/WinHue3#172]
I can't make hotkeys because whenever i try to click on the "**_Name_**" box, an empty drop-down menu appears.

_Am i doing it wrong or is it a bug?_

**Comment by Hyrules** [comment]
Indeed this is a bug. It's supposed to be a textbox not a drop down box. Here you can use this version meanwhile.

[WinHue 3.0.2214.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1821921/WinHue.3.0.2214.0.Setup.zip)

**Comment by Hyrules** [comment]
Fixed in the latest issue
