### ISSUE TITLE
0% Brightness should be off

### ISSUE THREAD

**Issue by riahc3** [Hyrules/WinHue3#173]
If I turn on the light and its set to read the brightness slider, if I set it to 0% brightness, it should stay off. 0% brightness IMO (and Philips) is no brightness at all, which is off.

**Comment by Hyrules** [comment]
0 Bri in the hue api is not off. the Bri value is not a percentage but a byte value from 0 to 255 (256) so is the slider. 0 is the dimmest you can get and 255 is the brightest.
