### ISSUE TITLE
OSRAM SMART+ on/off plug

### ISSUE THREAD

**Issue by jandegr** [Hyrules/WinHue3#176]
Unable to switch OSRAM SMART+ on/off plug on.

message shown is
Type 6, parameter, bri, not available at address /lights/16/state/bri.

Switching it off works :)

not working with versions 3.RC.1 up to 3.0.2128.0

The youngest version I found to be working with the on/off plug is 3.beta.27
With this version the message is 
address /lights/16/state/on to True

this is how it is defined in the lights section in a v2 brigde 

"16":{"state":{"on":false,"alert":"select","mode":"homeautomation","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":null},"type":"On/Off plug-in unit","name":"On/Off plug 1","modelid":"Plug 01","manufacturername":"OSRAM","productname":"On/Off plug","capabilities":{"certified":false,"control":{},"streaming":{"renderer":false,"proxy":false}},"config":{"archetype":"classicbulb","function":"functional","direction":"omnidirectional"},"uniqueid":"84:18:26:00:00:0c:a8:4f-03","swversion":"V1.04.12"}} 

Thanks a lot for the nice app.

**Comment by Hyrules** [comment]
I will fix this asap I know why this is happening.

**Comment by Hyrules** [comment]
Try this version and let me know if this fixes it.

[WinHue 3.0.2157.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1848600/WinHue.3.0.2157.0.Setup.zip)

**Comment by jandegr** [comment]
Working fine,
THX !!!

**Comment by Hyrules** [comment]
Fixed in the latest version
