### ISSUE TITLE
Bridge update required?

### ISSUE THREAD

**Issue by tmask2** [Hyrules/WinHue3#177]
Hello just found this software but having issues getting started. It only tells me "bridge update required" etc but there are no updates available for my bridge. The api verison I am using is 1.24.0 and the winhue version says 3.0.2128.0  am I doing something wrong?

**Comment by Hyrules** [comment]
Can you send me a log file ? I would like to see what happen when you start the app. The logfile is located in the %APPDATA%\WinHue\log folder. (paste it directly in the bar in windows explorer) get the latest log and put the file here. Please do not post the whole content of the file here.

**Comment by tmask2** [comment]
[WinHue3 2018-03-27.txt](https://github.com/Hyrules/WinHue3/files/1853986/WinHue3.2018-03-27.txt)

**Comment by Hyrules** [comment]
You are running the API versin 1.11 that's why you get the error message. You need to update the bridge in order for winhue to work properly. You can always go to the settings and uncheck Check for bridge version. This should bypass the message and let you use the app. Note that you should update the bridge anyway to avoid problems.

**Comment by tmask2** [comment]
![image1](https://user-images.githubusercontent.com/3084056/37998202-b3b3d5de-31eb-11e8-9754-9e33a3b3cfa7.jpg)
settings screen shot from the winhue app

**Comment by Hyrules** [comment]
Odd... you logs says otherwise...

2018-03-27 12:57:45,039 [1] DEBUG WinHue3.Functions.Application_Settings.Settings.WinHueSettings [LoadBridges:243] ==> Loading bridge settings : {
  "BridgeInfo": {
    "00:17:88:20:df:41": {
      "ip": "192.168.1.XXX",
      "apikey": "132c0959d4b574474dXXXXXXXXX",
      "apiversion": "1.11.0",
      "swversion": "01030262",
      "name": "Philips hue"
    }
  },

**Comment by tmask2** [comment]
That is very strange lol, ill try unchecking like you said thanks for the tip!

**Comment by Hyrules** [comment]
ok try this. go to appdata folder like earlier and change the apiversion in the WinHueBridges.set this file is a text file you can edit it with notepad++ or notepad.

**Comment by tmask2** [comment]
Editing the WinHueBridges.set file worked! Thanks so much!

**Comment by Hyrules** [comment]
I'll have to check this. If you updated the bridge with another app WinHue might remember it as an old version.

**Comment by tmask2** [comment]
That may be what happened. I was having issues updating it through winhue so I did it through my hue kindle app

**Comment by Hyrules** [comment]
I have fixed this issue in the next release. The bridge will get a fresh apiversion every time it connects so this should not happen again.
