### ISSUE TITLE
Compatibility with cheap bulbs from Wish.com

### ISSUE THREAD

**Issue by vanguard89** [Hyrules/WinHue3#179]
Hi.

Wondering whether WinHue 3 can work with cheap bulbs and wifi rgb controllers from China?

**Comment by Hyrules** [comment]
Philips hue does not use wifi protocol but zigbee. Winhue uses the philips hue api so I would be suprised it it was working with it. It's made for the philips hue system so it will unfortunately not work with anything else and is so embedded with the hue api that adapting it would require a rework of the whole code.
