### ISSUE TITLE
'transitiontime' Slider is Disabled when selecting a Non-Colour Lamp

### ISSUE THREAD

**Issue by banksio** [Hyrules/WinHue3#180]
WinHue version : Latest dev
Bridge api version : 1.25.0
Light model : Non-colour

The transitiontime slider does not get enabled when selecting a non-colour lamp (White/White Ambiance), it remains disabled. Just noticed this whilst doing some theming work.

**Comment by Hyrules** [comment]
Yep it seems to happen to every light in my case.

**Comment by Hyrules** [comment]
Fixed in the latest version
