### ISSUE TITLE
Pairing not working

### ISSUE THREAD

**Issue by drujd** [Hyrules/WinHue3#186]
WinHue version : 3.0.2331.0 - RC6
Bridge api version : 1.24.0

Pairing stopped working in 3.0.2331 clean install (with configuration deleted). Clicking Pair and pressing the pair button on the bridge does not do anything. Downgrading back to RC5 fixes the problem.

**Comment by Hyrules** [comment]
I will take a look at this right now.

**Comment by Hyrules** [comment]
Yep I have this bug too will fix it.

**Comment by Hyrules** [comment]
[WinHue 3.0.2336.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/2180444/WinHue.3.0.2336.0.Setup.zip)
You can try this version and let me know if the issue is fixed. It seems to be working on my side.

**Comment by Hyrules** [comment]
Happy to know this is fixed. I have posted a new version on the release page so people can get this version.

**Comment by drujd** [comment]
Yup, works in 3.0.2338.
