### ISSUE TITLE
I am dumb pls help me :/

### ISSUE THREAD

**Issue by Berny-Design** [Hyrules/WinHue3#189]
Hey, 

I wanted to create a Hotkey to switch on/off all lights.
1st press on 2nd off.
I tried it now for 1h but I dont get it working :(

https://i.imgur.com/und7nVY.png

**Comment by Hyrules** [comment]
Basically you can't. WinHue does not work that way with hotkey. Hotkeys are all single press and will trigger whatever you have chosen as a scene or settings for the light. In your case you will have to create 2 separate hotkeys one for on and one for off.

**Comment by Berny-Design** [comment]
okey, thank you for the info :) that was awesome
