### ISSUE TITLE
BUG: Unexpected exception upon inserting a rule

### ISSUE THREAD

**Issue by wo-rasp** [Hyrules/WinHue3#19]
To use multiple Philips Dimmer Switches with the Bridge, the iOS App uploads a set of rules. With Windows, those rules have to be created manually.

I can enter all data and configuration information required, however when I press the button to create the rule, I get a pop-up message box: "Sorry but an unexpected exception occured. Please report the exception ....". I have no ther choice but to Press the OK button, and WinHue3 terminates.

After restart of the Hue3 app, i can edit the rule and everything works fine.

**Comment by Hyrules** [comment]
can you give me a log of the application when the exception occurs i will take a look at it thanks.

**Comment by wo-rasp** [comment]
[log 2016-09-25.zip](https://github.com/Hyrules/WinHue3/files/506386/log.2016-09-25.zip)

I have uploaded two log files with similar issues.
I currently use the following devices to control my bulbs:
- 1 Gen2 Bridge
- 3 white lamps (Eingang, Sekretaer, Buero).
- 2 Dimmer Switches (Flur, Sekretaer).
- 2 Lumia 620 (Wp8.1 with Huetro V2.3)
- 1 Raspberry (pilight)
- 1 PC (W10 with Winhue Beta 18)

All 3 Lamps are members of Group 1.
I use the dimmer switches as wall mounted devices to turn all lamps ON, OFF, DIM UP / DOWN (in increments of 30 Units)
The pi provides a standard WEB browser interface to give others access for controlling all lamps individually (without the need to register with the bridge)

**Comment by Hyrules** [comment]
Yep can replicate it. I'll get you a fixed version tomorrow. I've almost finished fixing the bug.

**Comment by Hyrules** [comment]
sorry i wasn't able to get you a fix yesterday. I got a weird bug while trying to fix this one it may take a couple more days to sort this out.

**Comment by Hyrules** [comment]
Here you go try this and let me know if you still have the error.

[WinHue 3 BETA 19 Setup.zip](https://github.com/Hyrules/WinHue3/files/512456/WinHue.3.BETA.19.Setup.zip)

**Comment by wo-rasp** [comment]
Nope, it still throws an exception.

 

Wolfgang

Von: Hyrules [mailto:notifications@github.com] 
Gesendet: Donnerstag, 6. Oktober 2016 00:30
An: Hyrules/WinHue3
Cc: wo-rasp; State change
Betreff: Re: [Hyrules/WinHue3] BUG: Unexpected exception upon inserting a rule (#19)

 

Here you go try this and let me know if you still have the error.

WinHue 3 BETA 19 Setup.zip <https://github.com/Hyrules/WinHue3/files/512456/WinHue.3.BETA.19.Setup.zip>

**Comment by wo-rasp** [comment]
Hi,

 

I installed beta 19 without and started the program directly after install.

After a reboot of the machine it is working now.

The button “Create Schedule” that was previously (before the reboot) greyed out is now active as well and allows editing of schedules as well.

 

A minor issue:

When a new rule is created the field for Name: is populated with the string ‘newRule’.

However actually if this field is not populated manually, a popup box is shown:

 

One or more errors occurred while creating the object:

Type : 5, invalid / missing parameters in body at address /rules/name.

                                      <ok>

 

I think this is due to the fact that the field is actually empty.

 

Kind regards

Wolfgang

 

Von: Hyrules [mailto:notifications@github.com] 
Gesendet: Donnerstag, 6. Oktober 2016 00:30
An: Hyrules/WinHue3
Cc: wo-rasp; State change
Betreff: Re: [Hyrules/WinHue3] BUG: Unexpected exception upon inserting a rule (#19)

 

Here you go try this and let me know if you still have the error.

WinHue 3 BETA 19 Setup.zip <https://github.com/Hyrules/WinHue3/files/512456/WinHue.3.BETA.19.Setup.zip>

**Comment by Hyrules** [comment]
yes the text written in that field is just an watermark and not actually in the field. There is already a check in place when you create the rule but not if you empty an edited rule name I will correct that. Create Schedule is always greyed out unless you select an object that you can create a schedule on such as Light or group.

**Comment by Hyrules** [comment]
This version should fix the rule name bug.

[WinHue 3 BETA 19 Setup.zip](https://github.com/Hyrules/WinHue3/files/514989/WinHue.3.BETA.19.Setup.zip)
