### ISSUE TITLE
Default Sort ComboBox in App Settings has no effect

### ISSUE THREAD

**Issue by banksio** [Hyrules/WinHue3#190]
- WinHue version : 3.0.2338.0
- Bridge api version : latest

### Expected behavior

The defualt sort combobox on the View Settings tab in Application Settings will sort the items in the MainWindow when the selection is changed.

### Actual behavior

The combobox option appears to have no effect.

Just discovered this whilst working on the theming, thought it was my branch but appears to be broken on latest release as well.

**Comment by Hyrules** [comment]
yep i'll fix this in the next release.

**Comment by Hyrules** [comment]
I see what is happening here. it works if you close the app and reopen it but not when you just edit the sitting I have corrected the bug. It will now refresh the view when you change the sorting order after closing the settings window.

**Comment by Hyrules** [comment]
Should be fixed in the latest version
