### ISSUE TITLE
Slow dim over several hours

### ISSUE THREAD

**Issue by GeorgeSpelvin** [Hyrules/WinHue3#191]
### Your setup 
WinHue version : (eg. 3.0.233)
Bridge api version : SW 1806051111
Light model : (simple white bulbs)

Sorry but this isn't an issue per se.  It's a matter of not knowing how to use the software.

I'm wanting to do just a simple task (but, apparently, too complex for a Hue Formula): 
    I want to slowly fade my living room lamp over the course of an evening.  Specifically, go from 100% brightness at 9pm to 20% at 1am (or a 1%/3minute drop if that helps)
WinHue seems robust enough that I'm betting it can do that but, without documentation, I have no idea how to implement it.

Can anyone point me in the right direction?  Thanks.

**Comment by Hyrules** [comment]
you can use the transition slider to do that and set it to the transition
time required. select a light or group and set the slider to n(being the
time you want) minutes and set the brightness slider to minimum and it will
dim over that time.

**Comment by Hyrules** [comment]
you can also create a scene that trigger to 100% on and then right after create another scene that goes to 1% with transition time both triggered with an schedule.

**Comment by GeorgeSpelvin** [comment]
Sorry for the delay in replying.
I found transition time in Scene creator; it's got a max time of 109 minutes (as opposed to the  desired 240).  Again, without documentation, I'm flying blind -- I suspect I pick my Lamp and add it to the scene, set the transition time to its max, brightness to brightest/254.  If these are the start parameters, I don't see a way to set end points (brightness when done) or, for that matter, how to actually -start- a scene running.

**Comment by Hyrules** [comment]
Unfortunately there is no documentation for WinHue you are welcome to help and try to make one of you like. You can try the wiki but it's limited and there is no documentation on the scenes. There is no start and end endpoint for a scene. It will start to whatever settings you are at the moment and go to the settings you choose. To understand WinHue you need to understand the philips hue system core concepts. (lights, groups, scenes, schedules,rules and resourcelinks) Those are not concepts related to WinHue but only my implementations of them. 

Scenes are something you would like the light to become. The settings you see is what you would like the scene to be. The transition is just how long it takes to become that from what you are at the moment to the settings you want. Starting a scene is simple as double clicking on it. If you have a transition of many hours you wont have any way other than looking at the log to see if your scene has been triggered or waiting. You can trigger a scene with a schedule if you want it to run every day at the same time. if you want your lights to start at 100% and dim over time you would have to set them at 100% somehow before firing the scene to dim them. You could create a schedule to turn the light on at 100% at x hour and another at x hour + 1 minute + 30 seconds fire the second scene which in turn dim them over time. 

For the maximum duration it's a hardware limitation of the bridge. the transition time is an uint16 or ( a 16 bits integer unsigned) so the maximum is 2^16 = 65536 ( x 100ms) 109 minutes or so. That means 0 to 65535 = 65536

Schedules are simple to create, you have the choice of 3 types schedules (run once) alarm (recuring) timer (every x amount of time)

![image](https://user-images.githubusercontent.com/3161577/45599784-e106a000-b9bf-11e8-9578-19f231d491fb.png)

it's really simple to create one just click on the schedule creator and the enter the settings you would like. (you will need to create your scenes before creating the schedules) if you want the schedule to happen every day you will need to choose an alarm and then select all the days of the week on the right plus set the time you like then save.
