### ISSUE TITLE
Feature Request: Blocking/Hiding lights

### ISSUE THREAD

**Issue by jaqb** [Hyrules/WinHue3#195]
WinHue version : (eg. 3.0.2838.0)
Bridge api version : (1.27)

I have a smart plug that acts as a hue light and I don't want it to be turned off by mistake.

Is it possible to block/hide the light (plug) from the main list and also (very important) blocking it from being affected by "All Off"

**Comment by Hyrules** [comment]
Implemented in the latest version.
