### ISSUE TITLE
WinHue cant find the Hue Bridge

### ISSUE THREAD

**Issue by Dewaslim** [Hyrules/WinHue3#196]
### Your setup 

WinHue version : (eg. 3.0.2338.0)
Bridge api version : dont know which api only the SW which is: 1809121051

### Expected behavior and actual behavior

Downloaded the newest Version and tried to connect to my Bridge. But the programm cant even find the bridge. Only message is: "bridge is not responding".

Im thinking that maybe my bridge is not on the newest firmware, but i used the app to update it and i registered the bridge at philipps. Other third party apps also cant find the bridge. I cant even connect with the debug app from phillips. Has anybody an answer?

**Comment by Hyrules** [comment]
if third party apps are not finding your bridge it will not work with WinHue. Are you trying to use WinHue with aything other than an authentic philips hue bridge ? I lknow that WinHue is designed to work with the philips hue bridg and will not work with other emulators or system which host a "false" bridge like alexa.

**Comment by Dewaslim** [comment]
Thanks for the quick respond!

Nope i use the official philips hue bridge. Im curios, because i cant find the Firmwarenumber on any Updatelists by Philips.

**Comment by Hyrules** [comment]
Is your bridge working with the philips hue official app ?

**Comment by Dewaslim** [comment]
Yeah it is, thats why im so frustrated why it wont work with anything else. It even updates the bridge.

**Comment by Hyrules** [comment]
There should be a log in the winhue folder in your appdata folder of your windows profile. You can upload it here so I can see what happens.

**Comment by Dewaslim** [comment]
[WinHue3 2018-10-03.txt](https://github.com/Hyrules/WinHue3/files/2442796/WinHue3.2018-10-03.txt)

I also tried to connect per IP adress, but this only shows up the message: "bridge is not responding"

**Comment by Dewaslim** [comment]
2nd Gen, the square one. Would it help to switch the bridge on and off again?

**Comment by Hyrules** [comment]
you could try pulling the power plug. There might also be something in your router config that causes this issue.

**Comment by Dewaslim** [comment]
Yeah i will look into the router config and maybe something ist blocking the bridge

**Comment by Hyrules** [comment]
Are you by any chances on a different subnet ? like your pc is on 192.168.1.X and the bridge is on 192.168.5.1 ? Also there might be a firewall or some security app blocking third party on windows.

**Comment by Dewaslim** [comment]
I will look for that, currently busy but after that i will have a look

**Comment by Hyrules** [comment]
let me know if you need any help with it.
