### ISSUE TITLE
slider control

### ISSUE THREAD

**Issue by pleg** [Hyrules/WinHue3#199]
### Your setup 

WinHue version : 3.0.3028.0

### Expected behavior and actual behavior

slider control does not respond to mouse wheel or keyboard action, only to mouse click.

### Steps to reproduce the problem

using the keyboard:
1) select slider by clicking it
2) try to use keys to move the slider (arrow keys, page-up/page-down, home, end)
3) interface responds but setting is not applied

using the mouse:
1) select slider by hovering over it
2) try to use the mouse wheel on it
3) interface does not respond

**Comment by Hyrules** [comment]
Keys and Wheel are not implemented on sliders. I will add this to the requested features.

**Comment by banksio** [comment]
The arrow keys do work on the transition time slider, I think maybe it's an issue with the bindable sliders?

**Comment by Hyrules** [comment]
This might be related to the hotkeys also. I'll have to take a look at this more closely. The keypress does not seems to go all the way to the sliders. Maybe the hotkey handle does not propagate the keypress properly.

**Comment by Hyrules** [comment]
Paritally implemented in the latest version it's the best I can do for now.
