### ISSUE TITLE
Osram Lightify Unavailable therefore not switchable, send command regardless

### ISSUE THREAD

**Issue by sharonna511** [Hyrules/WinHue3#202]
Hi 

I have a few  Osram Lightify Bulbs and Plugs. But they are always marked Unavailable and are therefore not switchable.
It would be nice if Winhue would just send the command to the bridge regardless of the state Unavailable. Because if i switch those lights in apps like huepro or via Home Assistant or direct via json they work perfect, so this is just Osram Lightify reporting the wrong state, but they are online.

WinHue version : Latest 3.0.3028.0
Bridge api version :  1.27
Light model : Osram Lightify

`{
	"state": {
		"on": false,
		"bri": 86,
		"ct": 370,
		"alert": "none",
		"colormode": "ct",
		"mode": "homeautomation",
		"reachable": false
	},
	"swupdate": {
		"state": "notupdatable",
		"lastinstall": null
	},
	"type": "Color temperature light",
	"name": "Bedlamp",
	"modelid": "Classic B40 TW - LIGHTIFY",
	"manufacturername": "OSRAM",
	"productname": "Color temperature light",
	"capabilities": {
		"certified": false,
		"control": {
			"ct": {
				"min": 153,
				"max": 370
			}
		},
		"streaming": {
			"renderer": false,
			"proxy": false
		}
	},
	"config": {
		"archetype": "classicbulb",
		"function": "functional",
		"direction": "omnidirectional"
	},
	"uniqueid": "84:18:26:00:00:0c:0a:14-03",
	"swversion": "V1.04.12"
}`

`{
	"state": {
		"on": false,
		"alert": "none",
		"mode": "homeautomation",
		"reachable": false
	},
	"swupdate": {
		"state": "notupdatable",
		"lastinstall": null
	},
	"type": "On/Off plug-in unit",
	"name": "Subwoofer",
	"modelid": "Plug 01",
	"manufacturername": "OSRAM",
	"productname": "On/Off plug",
	"capabilities": {
		"certified": false,
		"control": {},
		"streaming": {
			"renderer": false,
			"proxy": false
		}
	},
	"config": {
		"archetype": "classicbulb",
		"function": "functional",
		"direction": "omnidirectional"
	},
	"uniqueid": "7c:b0:3e:aa:00:a3:ce:8e-03",
	"swversion": "V1.04.12"
}`

Thanks for your work.
Regards Sharonna

**Comment by Hyrules** [comment]
I'm not sure if this is a bug or something that I would need to change. I don't see a unreachable property in the json which is typical to philips hue compatible bulbs. This might be why it's not working. I might be able to add an exception for this kind of bulb. I will take a look at this more closely asap.

**Comment by sharonna511** [comment]
I don't think it is a bug, i think you made it right, not to switch lights that are "reachable": false and therefore are offline/not connected to the bridge.
It's just that the Osram devices are nearly all the time "reachable": false even if they are online/connected, if you could add an exception for all "manufacturername": "OSRAM" that would be great. Thanks

**Comment by Hyrules** [comment]
No problem for that I will add an exception for the manufacturername OSRAM. I'll try to give you a test version soon.

**Comment by Hyrules** [comment]
you can try this version and let me know what happens :

[WinHue 3.0.3108.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/2540033/WinHue.3.0.3108.0.Setup.zip)

**Comment by Hyrules** [comment]
By the way The light will still show unreachable. I just forgot that part. It will be fixed in the final version.

**Comment by sharonna511** [comment]
Thanks i tested this version, but i see no change in behavior, double click on the lamp does not turn it on, neither does the on button in the bar above. I turned the lamp on via home assistant, then i can change the sliders in winhue. Otherwise not. I gather you don't have an osram bulb for testing this. i am willing to test this as much as you like.

**Comment by Hyrules** [comment]
I'll try to give you another version later today. As you said, I don't have any osram bulb. I use mostly Hue and LIFX bulb at home. One thing that could help is a dump of your bridge. I could load it on my side and see how WinHue react. Maybe just copy both osram light json into a text file and put it here for me to load. I can use that to test virtual osram bulbs.

**Comment by Hyrules** [comment]
got it thanks ! I'll do with that for now I'll be able to see what is happening here.

**Comment by Hyrules** [comment]
Here you can try this one and let me know what happens. Again i'm not sure this fixes it. If not send me the log with the next message. it's located in your appdata folder (not the one in program files)

[WinHue 3.0.3112.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/2544381/WinHue.3.0.3112.0.Setup.zip)

**Comment by TravelingDragon** [comment]
Woot!  You got it!
Thank you for your lightning fast response!

**Comment by sharonna511** [comment]
Hi sorry for the late response, i have not seen the mail till now. i tested the version and it works great it shows the osram lights as not grayed out and if i click them they turn on off, i also checked in my bridge if the light is currently reachable": false and that it is, so perfect its fixed. Thanks

**Comment by sharonna511** [comment]
here is the log, should you still need it.
[WinHue3 2018-11-21.txt](https://github.com/Hyrules/WinHue3/files/2604083/WinHue3.2018-11-21.txt)

**Comment by tursoe** [comment]
This work around is terrible.
Please du not put it in production.

The only right solution is to make the Osram plug reachable again.
Simple gulf the round button on it for 10-12 second to the relay make a click. Then perform a normal search in hue app / WinHue and its appears as reachable again.

Best regards
Christian

**Comment by sharonna511** [comment]
@tursoe i agree with you, they should be reachable, but if i have to pair them (plugs and lights) all the time again i would go nuts, it totally random, they are just bad products, i don't buy them again. @Hyrules if you don't want to put that in production i am okay with that, i can always switch via home assistant or other means.

**Comment by tursoe** [comment]
For me it only appears once within the past two years. I’ll have 5 plugs and there having firmware version 1.04.12.
I’ll will prefer that commands are send regardles of the teachable state but still are shown as unreachable.

**Comment by sharonna511** [comment]
I prefer that too, that would be ideal.

**Comment by Hyrules** [comment]
this could appear in a form of a settings in the app settings to bypass this problem. Right now this is applied only to OSRAM devices and not at large to any unreachable devices. The choice is yours. In my case I will still need to remove some code if you prefer not to do it,

**Comment by sharonna511** [comment]
With setting would be fine, so everybody has a choice, how the like it. I am fine with it, as it is now, add a setting for this fix, and leave it default off, i think that would be best.
