### ISSUE TITLE
Unable to set Hue Daylight sensor parameters in WinHue version 3.0.3028.0

### ISSUE THREAD

**Issue by Kaarsje** [Hyrules/WinHue3#203]
WinHue version : 3.0.3028.0
Bridge api version : 1.27.0
Light model : d.c.

Can not edit daylight sensor properties by
[1] rightclick icon->edit
[2]The properties window has an updown control for setting offsets sunrise/sunset.

As a result you can not set the GPS parameters.

 If the edit in the Daylight sensor icon is activated the program just ends without a trace.

The time offset controls in the properties window do not work. You can also not overtype the settings. 
BTW: The time indicated is not local time (last activation indicator gives probably GMT)

There are no special initial conditions. Just start the program and try to edit.

**Comment by Hyrules** [comment]
The GPS coordinates will never show in the Editor. When you set it it is set in the bridge and the bridge does not return the value of the GPS coordinates. it's the way the bridge works. Matter of security. What does the log gives when you set it ? does it show an error or a success ?

**Comment by Kaarsje** [comment]
Hi,

One problem is the edit function for the Daylight sensor, but there are
some other idiosyncrasies concerning GPS and offsets.

Can not set any Daylight parameters with desktop HueWindows 3.028. The
program just exits without trace when selecting "edit" for Daylight sensor.

 In the Winhue mobile 10 version time can be set, but not negative time.
However if I give positive time for sunrise X the properties windows WinHue
displays -X (that is:before sunrise). Hmm, I want the lamp on *before* the
sun sets and off *after *the sunrise has occurred.

I can give no logs because I can not start the edit/set routine itselves
(program exits), no info in the log either. Idem for error or success
notifications.  In the initialization I can see that the settings are
retrieved from the bridge, so far so good.
The time given is probably GMT, I do'nt know where GMT is translated to
local time.

Its a slowly deteriorating function. Couple of versions back GPS could be
set and read, time offsets positive and negative. Then the display function
disappeared (Philips security and privacy or whatever reasons). Offsets
stil programmable. Now nothing works, program just exits.
How does the bridge know where it is located ? Maybe it remembers the 2016
settings or misuses the region indicator for time ? It is peculiar that the
mobile version still has still working limited possibities for time offset
setting .. If I set a time offset via mobile, it goes to the bridge and the
desktop version can read it during initialization and opening of properties
window.

I tried the Windows "solves all" procedure (OFF-ON): . I deleted the
sensor. After restart it was back, but still uneditable. I also reinstalled
WinHue a couple of times.
Sometimes a deinstall does not remove all garbage. That gives then
problems. Maybe also here some leftovers are causing problems ?

**Comment by Hyrules** [comment]
No this is most likely a change that happen on the bridge since I last modified the Editor for the Daylight Sensor. I will take a look at this asap. Most likely a bug.

**Comment by Hyrules** [comment]
try the version in #202 and let me know if this fixes it for you.

**Comment by Kaarsje** [comment]
Yesss, edit Daylight sensor works now in 3.0.3108, no program exit.

I can set positive and negative offsets. I can turn on the lamp f.i. -15
minutes before sunset. I can turn off the lamp +15 minutes after sunrise.
The properties window of WinHue desktop displays the correct offsets. The
properties window does not allow edit of parameters although there are
up/down controls in the minutes fields,that is no problem..

However, in the mobile version W10 the offset parameters have *both* a
minus sign ! Although the minus sign is displayed in mobile, you can not
enter in a minus value in mobile. Interresting confusion of logic
somewhere.

Additional info: W7PRO plus MS Essentials as security and W10Home with
Defender as security both give a virus warning when downloading 3.0.3108.
This happens already during download so that is the end of the exercise.
 Luckily my 3th system W7PRO with a commercial paid for security program
(F-Secure) does not detect any virus problem. If I transfer the file to
f.i.W10Home +Defender there are no virus warnings and the program setup can
be executed without virus warnings. MS features I think.

**Comment by Hyrules** [comment]
glad to know this fixes the issue for you. The property grid on the main form as it is called is a read only control in WinHue. You cannot edit properties of objects with it. I will see if I can disable the up and down button there if they are not already.

For MS Security Essentials, i'm not sure why it shows as a virus. I can assure you there is no virus in WinHue. Maybe because it's an executable zipped inside a zip alone.

For the mobile version, like i`ve said many times over the years, WinHue is intended as a desktop application if you use it on a mobile phone you are on your own. I have no way of debugging phones and my main goal was to have a functionnal desktop app at the time I created it. Since in the beginning the hue system was intented for IPhones and Android only.
