### ISSUE TITLE
WHC error

### ISSUE THREAD

**Issue by TravelingDragon** [Hyrules/WinHue3#204]
Before submitting a request please make sure you are running the latest version of WinHue 
available in the release section of this site. Support will not be done on older version.

### Your setup 

WinHue version : 3.0.3028
Bridge api version : 3.9.0
Light model : (if you have a problem with a particular light)

### Expected behavior and actual behavior

I've been using the CLI for over a month.  It had integrated flawlessly with my smarthome.
I've modified PATH variable so calling the CLI only requires "whc"
typing: whc -lg
should give me a list of groups on the bridge

### Actual behavior
Since I updated to the new version of WinHue, I get: "An error occured while trying to..."
this general error occurs when I try to send any command via CLI
The WinHue app still successfully controls the lights.

### Steps to reproduce the problem

1) Windows Start, CMD (run as Admin, or not)
2) whc -lg (or -ll, or any light ctrl command)
3) error

In the case of a crash, please make sure to add a logfile containg the crash located in the %APPDATA%\WinHue3
to the issue you are opening.

Reviewing log files seems to indicate "PUT" is not an available resource & it is unable to "unserialize resource.  In an attempt to troubleshoot, I have copied the appdata file & removed the app, and deleted the remaining settings files.
I am hoping that a fresh start might restore functionality or allow me to re-sync the bridge.

Thank you for creating this!

**Comment by TravelingDragon** [comment]
Following up: the results are the same.  
Bridge is up to date
WinHue3 has been fully uninstalled & orphaned files deleted
reinstalled WinHue3, scanned & paired successfully with Hue Bridge
Confirmed functionality of GUI app
CLI still returns "An error occurred while fetching the list of groups"

(it seems I was mistake: API version number returns as 1.28 in log file)
log seems to indicate 
[WinHue3 2018-11-20.txt 2018-11-20.txt](https://github.com/Hyrules/WinHue3/files/2601454/WinHue3.2018-11-20.txt.2018-11-20.txt)
[WinHue3 2018-11-20.txt 2018-11-20.txt](https://github.com/Hyrules/WinHue3/files/2601456/WinHue3.2018-11-20.txt.2018-11-20.txt)

trouble with GET/PUT resource
Is this .NET?

**Comment by Hyrules** [comment]
can you try the version in #202 there was a fix pushed by a user a couple of weeks ago that might have fixed this. I don't seem to have this issue here so this might be already fixed

**Comment by TravelingDragon** [comment]
The error is after installing version 3.0.3112 the error went away.  However, the lights are not reacting.
-ll successfully pulls the light list. -lg successfully pulls the group list.
Commands return "successfully sent".  Log file indicates "success" as well.
Lights never change.

Worth note: the light list and group list take **much** longer now to return.  Formerly 1.5 seconds, now 5-6 seconds.

Next I will try pairing the bridge again.
[WinHue3 2018-11-20.txt](https://github.com/Hyrules/WinHue3/files/2602375/WinHue3.2018-11-20.txt)

**Comment by Hyrules** [comment]
No problem. I will take a look at this tomorrow.

**Comment by TravelingDragon** [comment]
So... after some reboots and button-mashing, I tested the CLI successfully.
FYI light and group list still polls slowly about half the time.  It seems like the time taken for a command to be sent/received is unpredictable as well. Sometimes nearly immediate, sometimes several seconds.
I would call it functional, just thought this info might be useful for future development.

**Comment by Hyrules** [comment]
Noted. I will still take a look at the delay your are getting to see if this happens on my side. 5 to 6 seconds seems to me relatively slow and abnormal.

**Comment by Hyrules** [comment]
I have taken a look at the command and with 17 bulbs I get an almost instant list of items on screen. It goes the same for the groups. Do you have anything on your machine that could make things slower like a firewall or an antivirus ?
