### ISSUE TITLE
Program shows empty mainform

### ISSUE THREAD

**Issue by dolorosus** [Hyrules/WinHue3#206]
### Your setup 

WinHue version : (eg. 3.0.3028.0)

### Expected behavior and actual behavior

A main window which shows  Bulbs, Groups etc...

### Actual behavior

Empty window after startup, Statusline shows :Type :-2, A unknown error occured at address  http://... 

### Steps to reproduce the problem

Start program

Logfile:
[WinHue3 2018-11-26.txt](https://github.com/Hyrules/WinHue3/files/2615795/WinHue3.2018-11-26.txt)

**Comment by Hyrules** [comment]
Will take a look at this. Thanks for reporting it.

**Comment by Hyrules** [comment]
Ok here we go : Sensor 28 named Tradfri WZ has a status of null. This is why its blank. I will add a fix to the next version.

**Comment by dolorosus** [comment]
merci pour la réponse rapide

**Comment by Hyrules** [comment]
Voici un version qui devrait corriger le problème le temps que je publie une nouvelle version.

[WinHue 3.0.3134.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/2617677/WinHue.3.0.3134.0.Setup.zip)

**Comment by Hyrules** [comment]
Glad to know it is fixed.
