### ISSUE TITLE
Pressing "Send" in advanced Creator leads to crash if form is empty

### ISSUE THREAD

**Issue by dolorosus** [Hyrules/WinHue3#207]
WinHue version :3.03134.0

1) Startup Winhue
2) Select "advanced creator"
3) press "send" with form empty -> Crash!

**Comment by Hyrules** [comment]
Here you go.

[WinHue 3.0.3152.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/2631034/WinHue.3.0.3152.0.Setup.zip)

**Comment by dolorosus** [comment]
Fixed.

Merci
