### ISSUE TITLE
Winhue crashes when mouse cursor is over the "Clone" menue entry

### ISSUE THREAD

**Issue by dolorosus** [Hyrules/WinHue3#209]
WinHue version : 3.0.3360.0
[WinHue3 2018-12-23.txt](https://github.com/Hyrules/WinHue3/files/2705606/WinHue3.2018-12-23.txt)

Steps to reproduce issue:
1) Startup Winhue
2) Click on Edit (the menue opens)
3) sweepdown with the mousecursor. As soon as the mousecursor hits "Clone" Winhue crashes.

**Comment by Hyrules** [comment]
I have fiexed it in the latest release. You can redownload the latest release.
