### ISSUE TITLE
Can't change brige IP after pairing 

### ISSUE THREAD

**Issue by mischka** [Hyrules/WinHue3#21]
It is not possible to change the IP or reset the bridge detection list.
After I change my router and reconnect the bridge it was not possible to connect to.
Because it is not possible to change the IP of the connected bridge or add a IP manually

**Comment by Hyrules** [comment]
I have seen this issue here in the last week. My ip address changed and I was force to edit the settings file in order to get the bridge working again. I will take a look to see if I can find a way to fix this.

**Comment by mischka** [comment]
Which file was it? May I also change the settings as a quickfix.

**Comment by Hyrules** [comment]
Go to "My documents" and then find the WinHue folder. You will see a WinHueSettings.set file. Just edit it with notepad or notepad++ and change the ip address of your bridge.

**Comment by mischka** [comment]
thx, works

**Comment by Hyrules** [comment]
Fixed in the latest version.
