### ISSUE TITLE
Feature Request: Custom Power-on behaviour for each light?

### ISSUE THREAD

**Issue by riahc3** [Hyrules/WinHue3#217]
After years, Philips finally added Power-on behaviour so....

Can WinHue3 now have custom settings for each light?

**Comment by Hyrules** [comment]
This has already been implemented in the latest version.

**Comment by Hyrules** [comment]
There might be a bug in the website @banksio otherwise you can get the lastest release here https://github.com/Hyrules/WinHue3/releases

**Comment by banksio** [comment]
It seems to download build 3367 for me - I'm not sure if the browser's cache could cause it to store out of date downloads. By the way download.html doesn't actually start the download, the main button on the [homepage](https://hyrules.github.io/WinHue3/) does. @riahc3 could you try that button and let me know the file it downloads? Thanks

**Comment by banksio** [comment]
Just opened WinHue out of curiosity to try this feature, and set my Bloom to custom, and seem to have found a bug (sorry about that):
![image](https://user-images.githubusercontent.com/30214760/51948337-03a1ce80-2420-11e9-9fe2-e6f04d95a80c.png)

**Comment by Hyrules** [comment]
some items might not have a on value try right click and reset it to null.

**Comment by banksio** [comment]
@Hyrules That works yeah. The error seems to occur on all of my lights though?

**Comment by Hyrules** [comment]
I'll take a look at the api see if I didn't miss something.

**Comment by riahc3** [comment]
Add the ability to pop up a window that shows this:

![image](https://user-images.githubusercontent.com/1131521/51948661-aad73380-2429-11e9-8a69-f191755c8e01.png)

Makes it a bit easier and quicker to select

**Comment by Hyrules** [comment]
@banksio  here is just no on value. custom is always on with some custom colors or brightness. @riahc3 I will consider adding sliders instead of the property box.

**Comment by banksio** [comment]
OK that makes sense so you could possibly just hide the on checkbox for all lights? Or maybe make it appear checked but disable it from being clicked.

**Comment by banksio** [comment]
I've tested the website as many different ways as I can now, and I'm convinced it does download the latest version - if there's any other issues suggesting it doesn't then I'll rework it. But in terms of the website, I'm happy for this to be closed.

**Comment by riahc3** [comment]
@Hyrules Thanks for considering it. It sliders generally just make it easierly visually to see.

**Comment by riahc3** [comment]
@banksio  Yeah, downloads are working now correctly as they should :)
