### ISSUE TITLE
Error when saving a new scene

### ISSUE THREAD

**Issue by martinlavoie78** [Hyrules/WinHue3#23]
I'm configuring my new setup. I've created a group with my 4 light.
I click create a scene. I enter "Blue" as name, i set blue color in step 2, Step 3 i add my 4 lights, and click "Save Scene".

It don't save and popup this error:
"One or more errors occured while creating the object:
Type : 4. method, POST, not available for ressource, /sscenes at address /scenes"

What does it mean ?

In event log i see the command :
Scene to be created : {"name":"Blue","lights":["1","2","3","4"],"recycle":false}

**Comment by Hyrules** [comment]
Just for my curiosity is that a typo at /sscenes or is it exactly the message you get ? I'm trying to figure if it's a string error of simply a typo before looking in depth in this bug. Note that I have found 2 bugs today in the scene creator. Also can you tell me which version of WinHue you are using and what version of the bridge you have. You will find the bridge version in the Bridge Settings window under Api Version.

**Comment by martinlavoie78** [comment]
It's a typo error i confirm it's wrote "/scenes", sorry ! ;o)

**Comment by Hyrules** [comment]
ok good. I'm looking into this right now. Still need the Api version. Sometimes when the bridge api is not up to date it could cause that error.

**Comment by martinlavoie78** [comment]
My bridge API version is 1.10.0
Sw Version is 01028090

**Comment by Hyrules** [comment]
Here you go... that's the problem. You need to update to 1.15.0. WinHue needs the latest version to work properly.

Here is a snippet from the Philips Hue API :

URL	/api/<username>/scenes/<id>
Method	PUT
Version	
1.1 - Deprecated as of 1.11 (Use POST instead)

**Comment by martinlavoie78** [comment]
Ok thanks a lot for the information ! I'm new with hue, could you please send me a link to a documentation for updating it ?

**Comment by Hyrules** [comment]
It's simple and WinHue can do that for you. When you open WinHue right beside the bridge settings button in the main windows there should be a Yellow exclamation mark button called Update Firmware. Just press it and it will update the bridge to the latest version. I will take 2 or 3 minutes to do so. There are not other way beside using Philips Hue App on your table or phone to update it.

**Comment by martinlavoie78** [comment]
I don't have an exclamation mark under the bridge settings button. I've attached a screenshot of my main screen in WinHue
![ashampoo_snap_2016 10 16_13h21m21s_001_](https://cloud.githubusercontent.com/assets/22871830/19419351/957fa2ba-93a3-11e6-8a51-3d63196352b5.png)

**Comment by Hyrules** [comment]
Is your Hue Bridge connected to the Philips Hue Portal ? That probably why you cannot see the update. If you go into the bridge settings window again you will see a Portal Status Tab. Click on it and tell me if the Connection property is connected as well a the other settings. You can post a screenshot. If you are not connected you will need to to so on philips hue portal. You will have to go here and register : http://www2.meethue.com so your bridge can receive the updates. It might take a couple of hours before your bridge gets the update.

**Comment by martinlavoie78** [comment]
Ok!!! Thanks for the information; i will register and let it get the update. I will update this post. Thanks !

**Comment by martinlavoie78** [comment]
Hi ! Once firmware updated it works ! But when i click Save Scene the app crash (i joined picture). But when i re-open the app the scene is there... I can work whit that for now. 
![ashampoo_snap_2016 10 16_15h57m43s_001_](https://cloud.githubusercontent.com/assets/22871830/19420450/9878c292-93b9-11e6-946d-21b864b3f93e.png)

**Comment by Hyrules** [comment]
Yes I know of that bug. Here try this version it should be fixed.

[WinHue 3 BETA 20 Setup.zip](https://github.com/Hyrules/WinHue3/files/532071/WinHue.3.BETA.20.Setup.zip)

**Comment by martinlavoie78** [comment]
Yes now it works, thanks !

**Comment by Hyrules** [comment]
This will be fixed in beta 20.

**Comment by uwe1515** [comment]
Hello!
I have installed the beta20 version and also I have the firmware 1.15.
The program still breaks and crashed when editing scenes. I can not change any scene. Create new ist in order, but do not change a scene. Its the same exception.
greetings
Uwe

**Comment by Hyrules** [comment]
Please post a log with the error. I will take a look at this.

**Comment by Hyrules** [comment]
Fixed in beta 21. Download on main page.

**Comment by uwe1515** [comment]
Thanks for the quick help. The error is gone, but some changes to the scene did not save changes.
I know but no rule.

**Comment by Hyrules** [comment]
I'll check this as soon as possible.

**Comment by uwe1515** [comment]
a little help for you: new scenes can not be activated and new scenes are not displayed in the original hue-app. now winhue does not store in accespoint

**Comment by Hyrules** [comment]
Here you can try this version this should finally be fixed.

[WinHue 3 BETA 22 Setup.zip](https://github.com/Hyrules/WinHue3/files/540389/WinHue.3.BETA.22.Setup.zip)

**Comment by uwe1515** [comment]
Thank you very much . now it's working.
But the new scenes from winhue are not to be seen in the original hue -app (android)

**Comment by Hyrules** [comment]
This in mostlikely something that Philips programmed themself in the android app. I have no way of controlling what the android app displays. There is also nothing special when i'm creating a scene. I use the same api as philips uses to create scenes from their app. So chances are the android app is ignoring the scenes that are not created by the application. The scenes created in the android app to my knowledge are rather special and are kinda stored both locally and on the bridge. If the android app does not create the scene it wont show in the android app.

**Comment by uwe1515** [comment]
Its ok!
regards
Uwe
