### ISSUE TITLE
Philips hue motion sensor

### ISSUE THREAD

**Issue by Klaus-THX** [Hyrules/WinHue3#25]
i don´t know if this is the right place to post this and my English is not the best

i have a Philips hue motion sensor and can´t use it, because i don´t have android or iOS

with winhue 3 beta 21 i was able to switch the lights on when motion is detected but i don´t know how to switch the light of when no motion is detected after a period of time.

is this possible ?

**Comment by Hyrules** [comment]
Surely you would have to create a rule. Try creating a rule which have the presence variable false and last updated property changed (DX) and in the action set your light off.

**Comment by Klaus-THX** [comment]
it is not possible to set false when dx is selected

**Comment by Hyrules** [comment]
You need 2 conditions 
- present = false
- lastupdated = dx

**Comment by Klaus-THX** [comment]
when i create a rule i can select the hue motion sensor
than i can select lastupdated and dx
but there is no presence to select - only lastupdated

**Comment by Hyrules** [comment]
Then I will need to update WinHue to support the motion sensor.

**Comment by Klaus-THX** [comment]
ok, thank you for your help

**Comment by Hyrules** [comment]
Here you can try this version. It might work or not I cannot test it I don't have a Motion sensor.
[WinHue 3 BETA 22 Setup.zip](https://github.com/Hyrules/WinHue3/files/546474/WinHue.3.BETA.22.Setup.zip)

**Comment by Klaus-THX** [comment]
thank you
now i can set all parameters
i have to test more and learn more about the hue api - but for now it works for me.

i set for light on:
lastupdated - dx
presence - eq - true

for light off:
lastupdated - dx
presence - eq - false

**Comment by Klaus-THX** [comment]
I think the philips hue motion sensor is not full supported now.
it has 3 sensors (temperature / motion / ambient light) 
in winhue 3 beta 22 i can only select lastupdated when creating a rule for temperature or ambient light sensor.

![ambient](https://cloud.githubusercontent.com/assets/22985922/19878292/12cbe4a0-9fe7-11e6-9126-4ee81cced64f.PNG)
![motion](https://cloud.githubusercontent.com/assets/22985922/19878290/12c9663a-9fe7-11e6-8b47-7a03be2b1e5f.PNG)
![temp](https://cloud.githubusercontent.com/assets/22985922/19878291/12ca68be-9fe7-11e6-8e7f-2b95f46c18c3.PNG)

**Comment by Hyrules** [comment]
There is no mention of a ambient light and temperature variable in the philips hue motion sensor api. Although there is an new temperature sensor from philips in the supported devices which gives the ambient temperature but this is another completely different sensor.

**Comment by Klaus-THX** [comment]
maybe the have not published the full api yet.
in description of the motion sensor i can only find motion and light sensor - not temperature.

i only own a hue bridge, three color lights and a hue motion sensor.
after insert batteries in the motion sensor - the three sensors was found by winhue 3 - that is all i know ;)

sry for my bad english

**Comment by Hyrules** [comment]
I have ordered a hue motion. I should have it next monday. I'll see if there is anything more about the motion sensor.

**Comment by Klaus-THX** [comment]
I didn't expect that

Philips can be glad that you're doing the job that Philips should do for windows

thank you

**Comment by Hyrules** [comment]
Just found the ambient light sensor hidden lower in the page of the software sensor. I will be able to implement it.

**Comment by Hyrules** [comment]
I have received my motion sensor. Working on it right now.

**Comment by Klaus-THX** [comment]
any news about the motion sensor ?

**Comment by MarcoSpoenemann** [comment]
Look at the lastest beta. I've got mine working.

**Comment by Klaus-THX** [comment]
ok, i installed the latest beta (22)

but while creating a rule i can only select lastupdated for ambient light sensor

is this correct or a bug ?

**Comment by Hyrules** [comment]
try beta 23 located in issue #29
