### ISSUE TITLE
New Sensors missing

### ISSUE THREAD

**Issue by MarcoSpoenemann** [Hyrules/WinHue3#26]
Philips released new Sensors.

We need support of Hue temperature sensor, hue motion sensor and hue ambient light sensor.

Maybe have a look at Q42.HueApi -Repository.

**Comment by Hyrules** [comment]
I'm already supporting the Motion Sensor. Take a look at issue #25 which is now closed. There is a alpha hidden in the thread that supports the motion sensor. The temperature sensor is in the api but there is no hardware at the moment that uses it. As for the ambient sensor it is not showing in the api yet. So I don't know how to implement it.

**Comment by Hyrules** [comment]
this is fixed in the latest beta 22.

**Comment by MarcoSpoenemann** [comment]
There is a typo in your code. ZLLLightlevel should be ZLLLightLevel in your switch statement.
After changing it, it works well. Thanks!

**Comment by Hyrules** [comment]
Corrected Thanks !
