### ISSUE TITLE
Enable/Disable schedules from rules

### ISSUE THREAD

**Issue by MarcoSpoenemann** [Hyrules/WinHue3#28]
Hey,

it would be really cool, if we can enable or disable a Schedule from a Rule. One scenario could be to enable a schedule, which turns off a light after a few minutes, when presence from a motion sensor is set to false.

Have a look: http://www.developers.meethue.com/content/lights-autooff

Regards
Marco Spöneman

**Comment by Hyrules** [comment]
I'll see what I can do about this.

**Comment by Hyrules** [comment]
Will be available in the next release.
