### ISSUE TITLE
Can't make hotkey

### ISSUE THREAD

**Issue by Tr3v0rC** [Hyrules/WinHue3#29]
I am unable to set a hotkey.... Any combo I make it says "Hotkey already assigned by another process. Please select another key combo and try again." Do I need auto hotkey? Or is it something else?

Thanks!

**Comment by Hyrules** [comment]
yes i am aware of this bug. i'll have it fixed in the next version.

**Comment by Tr3v0rC** [comment]
Awesome any eta?

**Comment by Hyrules** [comment]
i'll send you a fixed version tomorrow.

**Comment by Tr3v0rC** [comment]
Thanks

**Comment by Hyrules** [comment]
Here you go.

[WinHue 3 BETA 23 Setup.zip](https://github.com/Hyrules/WinHue3/files/581857/WinHue.3.BETA.23.Setup.zip)

**Comment by Tr3v0rC** [comment]
Thanks
