### ISSUE TITLE
[Feature Request] Spreadsheet view of scenes and bulbs they control 

### ISSUE THREAD

**Issue by fiveseven808** [Hyrules/WinHue3#3]
I just counted and I have 66 scenes now controlling 10 lights. Many scenes have the same name, and in one case, two scenes control the same lights and have the same name, one is locked and the other isn't. It's a bit confusing. 

I'd like to request a list/detailed view of the current scenes

Something a little like this in the scene area 

| Scene       | Light 1       | Light 2| Light 3 | Light 4| Locked|
| ------------- |:-------------:|:--------:|:----------:|:---:|:---:|
| Bright      |  Assigned | Assigned | Not Assigned| Not Assigned | yes|
| Bright      |Not Assigned     |   Not Assigned| Not Assigned | Assigned| no|
| Read  |Not Assigned     |   Not Assigned| Not Assigned| Assigned|  yes|

**Comment by fiveseven808** [comment]
Now that I think about it, if you ever decide to implement something like this, maybe the same could be done with the Bulbs section? Seeing as you don't reflect the color of the bulbs in the "state" image/picture of the bulb, if there were a spreadsheet like view where you could easily see the color mode and numerical status of each bulb's attribute, it would be nice.

**Comment by Hyrules** [comment]
It's doable but not in the main view. That would have to be a separate view for each type of object. I don't know if you tried it or noticed it but you can pull the property box out of it's location and resize it. it's some kind of grid view.

**Comment by Hyrules** [comment]
Here you go you can try [This release](https://github.com/Hyrules/WinHue3/releases/download/beta_16.1/WinHue.3.BETA.16.Setup.exe)  for the scenes mapping view. I'll implement something similar for the lights.

**Comment by fiveseven808** [comment]
Very cool!!! I like it! Could you make it so I can double click on the scene and activate it?

**Comment by Hyrules** [comment]
No problem.

**Comment by Hyrules** [comment]
This request has been implemented in beta 16.
