### ISSUE TITLE
Crashes (NPE) when attempting to create new scene

### ISSUE THREAD

**Issue by erlendaakre** [Hyrules/WinHue3#33]
Caused by:
1. Open WinHue 3 Beta 22.
2. Click the Create a Scene button on toolbar.
3. Enter name
4. Select colour
5. Select one or several lights
6. Click the add button (below list of lights)
7. Application crashes due to nullpointer exception

![crash](https://cloud.githubusercontent.com/assets/1230673/20272853/23a37b76-aa87-11e6-8288-b5517c909587.png)

[log 2016-11-14.txt](https://github.com/Hyrules/WinHue3/files/589832/log.2016-11-14.txt)

**Comment by Hyrules** [comment]
Yeah can reproduce that. I will fix it in the next version thanks for reporting it.

**Comment by Hyrules** [comment]
Try beta 23 and let me know if this is fixed.

**Comment by erlendaakre** [comment]
Yup, working great now. Thanks!
