### ISSUE TITLE
Make the difference between generic and regular shortcuts more clear

### ISSUE THREAD

**Issue by Tr3v0rC** [Hyrules/WinHue3#34]
Its hard to tell what the "generic shortcuts" checkbox means. Maybe you could add a blurb explaining what it means.

**Comment by Hyrules** [comment]
Sure I can add something.

**Comment by Tr3v0rC** [comment]
@Hyrules Are these things you want me to add as issues?
Or would you rather me not suggest things like this?

**Comment by Hyrules** [comment]
There is no problem in suggesting stuff. I will tell you if I find it worth it or not. You can select feature or enhancement when suggesting those otherwise if it's an issue/bug I will try to reproduce the it and get more info before declaring it a bug.

**Comment by Hyrules** [comment]
done in beta 23.
