### ISSUE TITLE
Editing rules: Add property "transitiontime" to action does not work

### ISSUE THREAD

**Issue by Radarix** [Hyrules/WinHue3#36]
BETA 23
when editing rules I can add all properties to new action except 'transitiontime' (e.g. with value 9). 

The 'Add' button just does not bring the property into the action.

Thanks

**Comment by Hyrules** [comment]
Yes I can reproduce that. I will fix it.

**Comment by Hyrules** [comment]
Try this version it should be fixed.
[WinHue 3 BETA 24 Setup.zip](https://github.com/Hyrules/WinHue3/files/593190/WinHue.3.BETA.24.Setup.zip)

**Comment by Radarix** [comment]
Thanks a lot for the very quick fix.
Tested - works just great!
