### ISSUE TITLE
Cant install Re Install WinHue

### ISSUE THREAD

**Issue by Tr3v0rC** [Hyrules/WinHue3#37]
![image](https://cloud.githubusercontent.com/assets/13138669/20326514/2f3a2734-ab57-11e6-9561-64bdc3b2861b.png)

Can't reinstall winhue after uninstall. No there is no folder in that location:

![image](https://cloud.githubusercontent.com/assets/13138669/20326645/a885cfee-ab57-11e6-92f9-7f586665c679.png)
#

**Comment by Tr3v0rC** [comment]
I cant add labels fyi

**Comment by Hyrules** [comment]
Did you install with admin rights ?

**Comment by Tr3v0rC** [comment]
Sorry
My antivirus decided to auto sandbox it
