### ISSUE TITLE
Oops, redundant message

### ISSUE THREAD

**Issue by Tr3v0rC** [Hyrules/WinHue3#38]
![image](https://cloud.githubusercontent.com/assets/13138669/20327161/ee27e558-ab59-11e6-8737-8cc871d8b7a4.png)

This is completely my fault, but if that little popup thing (by the checkbox) was there before I asked you to make it more clear, I was wrong, I didn't realize it said anything, at this point there is no need for the message at the bottom.

**Comment by Hyrules** [comment]
Yes it was there I just made it more visible for people who don't hover.

**Comment by Tr3v0rC** [comment]
Now that I look at it. there are actually three messages, the hover, the button, at the one at the bottom.

**Comment by Hyrules** [comment]
Yeah I know. I'll remove the bottom one eventually.
