### ISSUE TITLE
HUEMOTION

### ISSUE THREAD

**Issue by mrcool1575** [Hyrules/WinHue3#39]
Hi I have a huemoton and I can't use it can you add something to make it work :)

**Comment by Hyrules** [comment]
Hue motion is already supported in WinHue.

**Comment by mrcool1575** [comment]
oh I found it but the toggle off can I set a delay? Sry for bad english

**Comment by mrcool1575** [comment]
and how can I make a light state rule so it only turn on when its dark?

**Comment by Hyrules** [comment]
for the delay I don't know if it is possible. I would also like to know myself. For the darkness part there are 2 options here. You either use the ambient light sensor dark or daylight properties or you use the daylight sensor daylight properties.

**Comment by mrcool1575** [comment]
the light sensor on the motion sensor and I dont know how to make a rule that's do this

**Comment by Hyrules** [comment]
Ambient Light sensor - dark
eq
true

Ambient light sensor - last updated
dx

Motion Sensor - presence
eq
true

Motion sensor - last updated
dx

after that you add the actions your want to trigger.

This is a best guess of what you need to do. I

**Comment by mrcool1575** [comment]
<img width="1643" alt="capture" src="https://cloud.githubusercontent.com/assets/23614454/20463813/df1cbfb2-af3b-11e6-931f-f61df35efdb6.PNG">

**Comment by mrcool1575** [comment]
<img width="1643" alt="capture" src="https://cloud.githubusercontent.com/assets/23614454/20463824/1db41b62-af3c-11e6-8b85-d6d2c41b1cbf.PNG">

**Comment by Hyrules** [comment]
Like i`ve said this is a best guess but there seems to be something that the bridge does not accept as condition for rules and it look like the dark state. You could try with the daylight sensor.

**Comment by Hyrules** [comment]
seems the rules does not allow more than one sensor at the time...

**Comment by mrcool1575** [comment]
oh why? and can it be fikst?

**Comment by Hyrules** [comment]
I will have to find if this is related to WinHue or the bridge.

**Comment by mrcool1575** [comment]
I think its the program

**Comment by Hyrules** [comment]
nope. It's the rule. You cannot have 2 dx operator in the same rule. So you need to have only one and the rule will check at that time the status of the other sensor.

**Comment by Hyrules** [comment]
To add a delay try this : add a ddx operator instead of a dx and use this as value PTHH:MM:SS replacing HH by hours, MM by minutes and SS by seconds. They can be zeros.
