### ISSUE TITLE
User Guide?

### ISSUE THREAD

**Issue by Craig-NZ** [Hyrules/WinHue3#40]
Is there a UG for WinHue3?  I have a lot of questions about how the program works and the meaning of several screens.

First one, what is 'Daylight' under Home|Sensors?  I didn't purchase such a device so wondering if this is embedded in the Philips bridge?  Can I remove it?

Another,  I have 8 rules for Dimmer 2 (Dimmer 2.1, Dimmer 2.2, etc).  Do these somehow reflect the actions of things like clicking the ON button repeatedly?

Craig

**Comment by Hyrules** [comment]
There is a small userguide in the Wiki part of the site. Top menu Wiki. Although it won't answer those questions. The Daylight sensor is embedded in the bridge. It's a software sensor from Philips. It give you the option to schedule scenes or actions based on the daylight. You can delete it although it might come back at some point when you will look for new sensors. Double clicking on rules does not do anything. Same goes for sensors and schedules. You can only trigger Lights , groups and scenes.

**Comment by Craig-NZ** [comment]
Thanks, that was very helpful.  I'll use other issues to ask questions so as not to bury them all under a single issue.
