### ISSUE TITLE
Dimmer rules

### ISSUE THREAD

**Issue by Craig-NZ** [Hyrules/WinHue3#41]
I notice that there are 8 rules automatically created for each sensor (dimmer).  But only 4 of them are really needed, one for each button.  Can I safely delete the other 4?

**Comment by Hyrules** [comment]
Yes you could delete all of them. You would just have to recreate them if you need them. I have done so for mine. I only have 4 of them. It's rather easy to create them once you understand them.

**Comment by Craig-NZ** [comment]
A question, how would I write a rule that would cycle through a series of scenes I specify, each time I click the ON button (on the dimmer).  When I click the OFF button it would reset to the start of the list.

In other words, I click the ON button and it shows scene 1 (all lights assigned to the dimmer are full on), I click again (maybe 3 or 4 seconds later) it shows scene 2 (all lights assigned to the dimmer are off except for bulb 1), etc.  I then click OFF button and it resets back to scene 1 which would have all lights assigned to that dimmer to OFF.  Clicking the ON button repeatedly would cycle through all the scenes assigned in the rule (ie, after last one, the next click would send first scene again).

The idea is for a room to be able to setup various scenes (e.g., all on, only 1 on as a nightlight, etc) and use the ON switch to change the scene or the OFF switch to reset and turn them all off.

**Comment by Hyrules** [comment]
I'm not sure this is possible. There is a bridge object that's called ressourcelinks but i'm not sure if this could work with them. Information on them is sparse because philips has not given any proper example of how to use them yet.

**Comment by Craig-NZ** [comment]
Can a rule send a message to an IP address?  When the ON button is pressed, a rule would send a notification to a windows application.  The application would see the press and then send a message to the bridge to change to the next scene.  The other method would be to have the windows app polling the bridge for changes in sensor state, but this would be very inefficient.  Having the bridge send out a notice would be far more efficient.

**Comment by Craig-NZ** [comment]
Essentially what we would be doing is moving some advanced processing from the bridge to a 3rd party app.  To do this requires the bridge to send events to the app.  Events would be any changes in the state of sensors or bulbs.

**Comment by Hyrules** [comment]
No. There is no way a bridge can send something. 

A rule affects only something inside the bridge. An external program can alter a sensor property like a value ( temperature, flag etc..) To do what you want you would have to create a program that communicate with the bridge in the same way WinHue does to send it's command and learn the Philips Hue API.

**Comment by Craig-NZ** [comment]
Okay, I'll play with the various dimmer button states and see if I can do it that way.  Thanks.
