### ISSUE TITLE
Add custom path to installer

### ISSUE THREAD

**Issue by MaddBomber83** [Hyrules/WinHue3#44]
Hello!  When installing, can you add a page where the user can select the folder to install?  I normally don't let programs install into the default 'Program Files xxx'.

Thank you for the consideration!

**Comment by Hyrules** [comment]
Sure I Can add the option to the installer. It will be available next release.

**Comment by MaddBomber83** [comment]
Awesome!  On a side note...  How are you adding labels?  I'll have to go look that up for my projects.

**Comment by Hyrules** [comment]
I'm not sure what you mean by labels ?

**Comment by Hyrules** [comment]
ok just go it. In Github when you see the list of issues there is a label button beside the filter. Just click on it an on the page there will be a button new label.
