### ISSUE TITLE
Home window not populated

### ISSUE THREAD

**Issue by jorgenseebach** [Hyrules/WinHue3#46]
Just starting the program, connection ok but nothing shown

[

**Comment by Hyrules** [comment]
see issue #42 it's the same problem. There is a fixed version in the topic you can use that.

**Comment by jorgenseebach** [comment]
Sorry, this version does not fix the problem
[log 2016-12-15.txt](https://github.com/Hyrules/WinHue3/files/655247/log.2016-12-15.txt)

**Comment by Hyrules** [comment]
Log does not help. I will need a dump of your bridge store to see what is causing the deserialization error.

**Comment by jorgenseebach** [comment]
Does this help?

[Huedump.txt](https://github.com/Hyrules/WinHue3/files/655533/Huedump.txt)

**Comment by Hyrules** [comment]
I'll check this tonight. I hope this contains the problem.

**Comment by Hyrules** [comment]
Here try this version and let me know if it works.

[WinHue 3 BETA 24 Setup.zip](https://github.com/Hyrules/WinHue3/files/656101/WinHue.3.BETA.24.Setup.zip)

**Comment by jorgenseebach** [comment]
Thank you, now there is a lot of items in the window.

Looking forward to working with it over the weekend
