### ISSUE TITLE
App Window not centered

### ISSUE THREAD

**Issue by wo-rasp** [Hyrules/WinHue3#49]
The App starts with a maximized window.
On systems with 1024*768 pixels, parts of the the APP are not visible on the screen.
With Beta 24 the upper left corner of the screen is about the character O in the Home tab (e.g. everything to the left of the O and above of the O is not visible. Due to the fact that the lower right corner is visible, i can resize the window, and then maximize it.

  
![h_24](https://cloud.githubusercontent.com/assets/7294039/21411784/67b05fe2-c7eb-11e6-9021-d88449e4abb8.jpeg)

**Comment by Hyrules** [comment]
On what device are you trying to run WinHue ? Device such as tablets are not supported. I'm suprised to see someone with a resolution of 1024x768. This resolution is only 3% of the actual devices browsing the web. The main Window minimum size is 1024x768 which would probably causes what you are experiencing. Reducing the size of the main windows will most likely cause some problems. As far as I can see the settings with the main windows is still set at Screen center. So this is certainly related to the resolution.

**Comment by Hyrules** [comment]
Next version will correct this. You can try the version in issue #51 if you want.

**Comment by Hyrules** [comment]
This is fixed in the next beta 25. I will release a new version soon,
