### ISSUE TITLE
Unstable? and Unable to change light brightness with GUI 

### ISSUE THREAD

**Issue by fiveseven808** [Hyrules/WinHue3#5]
So recently when I try to open up the latest BETA 16 , once in a while it freaks out and throws a weird error. Unfortunately I haven't been smart enough to screenshot it yet... 

On the other hand, a reproducible error is the inability to change a single light brightness through the GUI. Maybe my computer needs to be restarted, however when I click on a light, and try to move the brightness slider, the controls snap away as soon as I click on the slider. Quite frustrating. Any clues on how to diagnose? 

It's possible this may be an error from running Windows 10 Home Insider Preview Build 14379.rs1_release.160627-1607 

I have not tested the latest BETA 16 on my server yet so I cannot be sure, however the brightness bug is reproducible on this particular computer so I figured I'd report it.

**Comment by Hyrules** [comment]
Latest BETA 16 is a dev beta meaning that I will most likely be unstable. I cannot know if this is related to a Insider Preview Release of Windows 10 as I am using the latest official version. If you want me to debug I will need to see that weird error as well as the log of the application with the error in it. Open winhue, reproduce the error and send me the log of the application after so I can take a look at it. Thanks.

**Comment by fiveseven808** [comment]
This log was collected after opening the program, clicking on a light, turning it on, and trying to change the brightness. I was successful in changing the brightness, but immediately after, the light deselected itself. 

[log 2016-07-06.txt](https://github.com/Hyrules/WinHue3/files/350467/log.2016-07-06.txt)

**Comment by Hyrules** [comment]
Yeah ok I understand what is happening. In implementing the heartbeat for some reason it deselect the object every time it beat to refresh the lights states.

**Comment by fiveseven808** [comment]
Was looking to redownload the beta 16 (non 16.1). Couldn't find it anywhere. Could you please upload it? My server is running beta 15 still and I just realized the group XY command doesn't work in that one.

**Comment by Hyrules** [comment]
Check the release tab. I have release beta 16. This bug should be fixed in it.

**Comment by fiveseven808** [comment]
Very cool! Love the new features! :+1:  Thank you!!! 

This bug has been resolved!
