### ISSUE TITLE
In rules value sent to CLIPGenericStatus has wrong type

### ISSUE THREAD

**Issue by xandor9** [Hyrules/WinHue3#52]
If a rule is created which changes CLIPGenericStatus with PUT a rest request in the form {"status":"1"} is created but because it is an integer value it should be {"status":1} without quotation marks.

**Comment by Hyrules** [comment]
Note I will take a look at that.

**Comment by Hyrules** [comment]
I have fixed this bug. The next version should work properly.

**Comment by Hyrules** [comment]
This will be fixed in the next version. I will release a new version soon.
