### ISSUE TITLE
local time in new rules

### ISSUE THREAD

**Issue by derdegenhard** [Hyrules/WinHue3#53]
Please add time (time periods) as conditions to rules. (screenshot)
I can only change time conditions in rules, that were created with other apps, but i can't add them in new rules.
![image](https://cloud.githubusercontent.com/assets/19466716/21716902/eab78f7c-d40d-11e6-9571-4d28278c7529.png)

**Comment by Hyrules** [comment]
Noted I will add this possibility in the next version.

**Comment by Hyrules** [comment]
if I understand you well you would like the possibility to select an object other than a sensor as a condition like in this case the config localtime variable ?

**Comment by derdegenhard** [comment]
yes, so that my motion sensor triggers specific actions only between specified times.

**Comment by Hyrules** [comment]
Added in the new version
