### ISSUE TITLE
WinHue remembers legacy IP

### ISSUE THREAD

**Issue by BINARYADDlCT** [Hyrules/WinHue3#54]
After installing a new router, with a new subnet by default, my batch scripts won't work anylonger. I keep getting the response that the bridge under IP XYZ is not responding, although I deleted the old bridge and added the same bridge with the new IP via UI.

Here is the response (hence the new IP is 192.168.178.29):
Error getting light {}
An error occured while sending the light state to the bridge.
Type : -999, Bridge is not responding at address 192.168.2.100.

Everything within the WinHue UI works fine.

**Comment by Hyrules** [comment]
If you want to fix this quickly you could delete the settings file. By default WinHue saves the settings of the bridge for a quicker startup in a file which is located in your Document / WinHue folder. I know of this bug bug never fix it properly yet.

**Comment by BINARYADDlCT** [comment]
I found a settings file at "C:\Users\MYUSERNAME\AppData\Roaming\WinHue" and deleted it. Even after restarting and pairing with the new IP, I keep getting the info that the bridge is not responding at the old IP. Is there any other place, where WinHue might remember the old address?

**Comment by Hyrules** [comment]
Depending on the version you are using it might be in My Documents / WinHue or in the appdata roaming folder. Otherwise I don't store the bridge info anywhere else. If this happens there must be a bug somewhere else in the application. When you do the pairing procedure do you use the detect bridge button or you enter a manual ip or scan ? I will take a look at this when I get home tonight see if I cannot find something odd the in the ip manipulation parts of HueLib.

**Comment by BINARYADDlCT** [comment]
I am using the scan method to detect the bridge, and push the link button for the actual pairing.

**Comment by Hyrules** [comment]
I wonder if this is not related to the DNS. Try this, open a command line window and type ipconfig /flushdns (you shoud get a dns flushed message) and try again WinHue. I know that the IP scan portion use the local pc dns to get some info. Not sure if this could be it.

**Comment by BINARYADDlCT** [comment]
Flushing the DNS doesn't seem to help.

**Comment by Hyrules** [comment]
Ah geee i just reread your message and this is happening with WinHue console ! it's been a while since i tested it and yes there might be a bug there. I'll get back to you later tonight.

**Comment by BINARYADDlCT** [comment]
Don't stress. I'll be happy if you get to it when you find a chance :)

**Comment by Hyrules** [comment]
Can you tell me the command you are using with whc to see if I can reproduce the problem ?

**Comment by BINARYADDlCT** [comment]
I get a response with the old IP with this command: whc -l=1 --on=true

**Comment by Hyrules** [comment]
ok i know what's happening. Quick fix : copy your settings file that's located in the Appdata Roaming to your Documents / WinHue 3 folder. I changed the default folder for WinHue settings in last build and I forgot to change it in whc so it loads the old version of the file in the Document folder. I will fix this.

**Comment by BINARYADDlCT** [comment]
You're right. That worked. Thank you for your help at this indecent hour :) Donation incoming!

**Comment by Hyrules** [comment]
Thanks alot.
