### ISSUE TITLE
Missing file Utils\ValidateBindableBase.cs

### ISSUE THREAD

**Issue by MrHamaga** [Hyrules/WinHue3#56]
Hi, I forked your code base to see if I could somehow add "copy a rule"-logic so I don't have to create almost identical rules for each of my dimmers. 

After forking the winhue3.csproj file complains that the file Utils\ValidateBindableBase.cs does not exist. Could you provide the file or let me know the contents?

**Comment by Hyrules** [comment]
Did you fork the master or the dev branch ?

**Comment by Hyrules** [comment]
By yeah it's odd that I has not been synced. I will post the file here when I get home tonight.

**Comment by MrHamaga** [comment]
I'm currently looking at the dev branch. I'm not sure if I solved the issue, but I added a nuget reference to Prism.Validation, which allows me to compile and run the application. 

Now I just need to find the form for showing Rules :)

**Comment by Hyrules** [comment]
in the View folder. Form_RuleCreator2.

**Comment by MrHamaga** [comment]
I found that one, but that's for creating rules. 

I'm trying to figure out how you populate the lvMainObjects list with the different elements, among these the rules. I haven't worked with xaml before, so have to read up on it :)

**Comment by Hyrules** [comment]
Populating is done by binding. You only have to fill a variable with the objects you want and define the template. The template of the mainform lvMainObjects is defined in the XAML of line 106 in MainWindow.xaml. OldViews / MainFormView.cs contains the logic for the main form. Populating is done one line 1077.

**Comment by Hyrules** [comment]
If you want you can just wait instead of creating the function to clone another user just requested the same function. I will implement it in the next version.

**Comment by MrHamaga** [comment]
Cool, thanks. 

I'm a software developer who likes to tinker with small projects in my spare time. Some weeks ago I wrote my own small app for accessing my light bulbs, but yours is so much more elaborate than anything I'll ever get time to write. Now I'm looking for ways to tweak yours to my liking. 

I'll probably try to work in a translation in the rule actions for the dimmer buttons based on the 
definition from [https://developers.meethue.com/documentation/hue-dimmer-switch-programming](url). 

First I need to be able to copy my dimmer rules :) 

But don't sweat it, I'll just use what you make and be happy that my dimmers can be customized :)

**Comment by Hyrules** [comment]
I`ve been programming WinHue for the last 4 years if I remember well. Started with WinHue and now it's Winhue 3. I have been working on WinHue 3 for the most of the last 2 years in my spare time. My C# has improved alot since. I`ve learned many things in C# because of WinHue. If you have questions don't hesitate. I'll answer as best as I can.

**Comment by MrHamaga** [comment]
I'm trying to understand the public ICommand DeleteObjectCommand => new RelayCommand(param => DeleteObject()); - and how that is mapped to the context menu.

**Comment by MrHamaga** [comment]
Oh,I guess it's defined in   <MenuItem Header="{x:Static resx:GUI.MainForm_ListView_Context_Delete}" x:Name="mnuDeleteObject" IsEnabled="{Binding CanDeleteObject}" Command="{Binding DeleteObjectCommand}"/>  along with the methods to see if it's enabled.

**Comment by Hyrules** [comment]
That a part that I related to the binding of command. What it does is it's bound to the context menu button and when you click on it, it relays (thus the RelayCommand) the command by executing the private function called DeleteObjects.

**Comment by MrHamaga** [comment]
Yeah, it's starting to make sense :) do you have a roadmap or a product backlog for the issues you are working on?

**Comment by Hyrules** [comment]
No it's all here in the issue section or in my head. Right now (not at the moment) i'm recoding the mainform using a MVVM architectural pattern. It gives less code thus less possibility of bugs.

**Comment by MrHamaga** [comment]
Yay, I managed to copy a rule :) Let me know if you want to see the code.

**Comment by MrHamaga** [comment]
I have a weird experience regarding rules updating a sensor. When I first create the rule the sensor is updated correctly and the rule works. But if I update it, the sensor is no longer updating, thus making the rule not working. If I remove and add the action updating the sensor it works again. 

Do you have any idea why this could be? 

The only difference I can see between the two webrequests, is as follows (in the actions section):
Working:
`"address": "/sensors/21/state",
		"method": "PUT",
		"body": {
			"status": 3
		}`
Not working: 
`	"address": "/sensors/21/state",
		"method": "PUT",
		"body": {
			"status": "3"
		}`

Should I open another issue, or is it ok I just keep asking questions in this one? :) Or do you have other sources for communicating?

**Comment by Hyrules** [comment]
No this is a known issue #52 it will be fixed in the next version.

**Comment by MrHamaga** [comment]
Sorry, I didn't see that one. 

Again, let me know if you want me to make a pull request for the rule copying.

**Comment by Hyrules** [comment]
I suggest you wait until the next version because most of the mainform code has changed. Chances are what you implemented won't work with next version.

**Comment by MrHamaga** [comment]
I'll do that. Thank you for taking the time to respond to my questions.

**Comment by Hyrules** [comment]
For what it's worth I have added the missing file to the repo.

**Comment by MrHamaga** [comment]
Thanks, I see you corrected other references as well :) However you still refer the HueLib project by its binary and not as a project reference, this causes some problems when building the solution the first time.

**Comment by Hyrules** [comment]
Noted I will also correct that.
