### ISSUE TITLE
Sort items on the bridge and other feature request

### ISSUE THREAD

**Issue by tursoe** [Hyrules/WinHue3#57]
Hello.
Thank you for this awsome program.

Ill just need some aditional functionality.
Is it possible for you to implement a sorting routine on the lights, groups, sensors, scenes and rules view. Im thinking about alphabetic sort, both desc and acs.
Another great feature will be an field to display current item number, eg. bulb number 5, when selecting an item.
The last feature request I'll have today is an "copy rule" guide, allowing users to reuse same rules on different sensors just with the target as different, eg. group or lights...

Best regards
Christian Kragh

**Comment by Hyrules** [comment]
Sure all interesting feature that I can implement. I'll try to get those in the next version.

**Comment by tursoe** [comment]
Great
 I'll also working in some sensors with a lot of new features based on esp8266. But it's must go through wifi and can only send commands to the generic sensors. After that the sensor change state, the rules are fires. I'll using winhue to create these rules for controleinf the lights.

Christian

**Comment by Hyrules** [comment]
All those feature has been implemented in beta 25. I will release a new version soon.
