### ISSUE TITLE
Turn off a bulb?

### ISSUE THREAD

**Issue by Craig-NZ** [Hyrules/WinHue3#59]
If I turn power off to a set of bulbs, then turn the power back on, all the bulbs come on.  If I then double click on a scene which sets only one bulb to 50% brightness, it does that but it does not turn the other bulbs off.  I tried adding the other bulbs to the scene and setting the intensity to 0 but it still left the bulbs unchanged.  How do I setup a scene so it will turn off a bulb?

**Comment by tursoe** [comment]
Helle.
You could try set "on":false instead of "bri":0

If that doesn't work, maybe Hyrules can help.
Christian

**Comment by Hyrules** [comment]
I know for a fact that when you turn the power on and off it takes the bridge about 15 seconds to know it's of or on. Setting the intensity to zero won't work. You have to set them off like tursoe said. Setting a scene on will never turn the other bulb off unless you add them to the scene and set their state off. One can never really know which bulb you want to turn off unless you specify them.

**Comment by Craig-NZ** [comment]
Thanks guys, I didn't see the state setting .. will give that a try.
