### ISSUE TITLE
creating new sensor CLIPGenericStatus crashes winhue

### ISSUE THREAD

**Issue by phsdv** [Hyrules/WinHue3#60]
Trying to setup an IP sensor as described on [developers.meethue.com/documentation/how-use-ip-sensors](https://developers.meethue.com/documentation/how-use-ip-sensors) causes winhue3 to crash (using beta 24).
After restarting winhue3 the sensor is created but with CLIPGenericFlag instead of the CLIPGenericStatus I did put in.

**Comment by Hyrules** [comment]
There is a bug in version 24 with the sensor creator. I'm already aware of it and it is fixed in the next version of WinHue. I will release a new version soon.
