### ISSUE TITLE
Rules conditions missing one kind of states.

### ISSUE THREAD

**Issue by tursoe** [Hyrules/WinHue3#61]
The Rules editor missing the ability to use On state for lights and  Any_On and All_On state in groups as introduced in Bridge API 1.13.

Please implement this feature in rules since it is needed for motion sensors.

**Comment by Hyrules** [comment]
I will add this to the next release.

**Comment by Hyrules** [comment]
Did I say I hate the philips hue api docs ? It seem you can select objects as condition other than sensor. I'm not sure which by the way but groups seems to be allowed...

**Comment by Hyrules** [comment]
Implemented in the next version.
