### ISSUE TITLE
Crash on doupleclick on Scenes

### ISSUE THREAD

**Issue by mcmicha** [Hyrules/WinHue3#62]
Crashlog inside...

[log 2017-02-02.xml.txt](https://github.com/Hyrules/WinHue3/files/749132/log.2017-02-02.xml.txt)

**Comment by Hyrules** [comment]
Can you try the Beta 25 in the #51 issue and let me know if this is fixed. The code has completely changed since last beta and chances are this is fixed.

**Comment by mcmicha** [comment]
With the latest version, there is still the crash. The scene is called "Nordlicht"
[WinHue3 2017-02-02.txt](https://github.com/Hyrules/WinHue3/files/749219/WinHue3.2017-02-02.txt)

**Comment by Hyrules** [comment]
you can try the version in issue #51 at the bottom and let me know if it still crashes.

**Comment by mcmicha** [comment]
Sorry, i can't test ist.
I delete those scene.

**Comment by Hyrules** [comment]
no problem then. I will close the issue and someone can reopen it if they get it or just create a new issue.
