### ISSUE TITLE
Crash when selecting a RGB color

### ISSUE THREAD

**Issue by mcmicha** [Hyrules/WinHue3#63]
Crash when selecting a RGB color, on version [BETA 25](https://github.com/Hyrules/WinHue3/issues/51#issuecomment-276227691) 
Create a new scene.
Open "From Image" dialog.
Click on a color.
Click on "Select" = Crash

[WinHue3 2017-02-03.txt](https://github.com/Hyrules/WinHue3/files/751708/WinHue3.2017-02-03.txt)

**Comment by Hyrules** [comment]
BETA 25 is not ready to be an actual beta. Scene are not working yet so this is normal.
