### ISSUE TITLE
Crash on Bridge Detection and Pairing

### ISSUE THREAD

**Issue by MrRedHead** [Hyrules/WinHue3#64]
When the Bridge Detection and Pairing is started the program crash with the following error:
"Sorry but an unexpected exception occured. ..."

With WinHue BETA 24 started and WinHue BETA 25 started same behavour.

OS Name	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393

Log: 

[log 2017-02-05.xml.txt](https://github.com/Hyrules/WinHue3/files/752647/log.2017-02-05.xml.txt)

**Comment by Hyrules** [comment]
Do you have the UPNP Network discovery service in windows disabled ?

**Comment by MrRedHead** [comment]
That's it: Starting the SSDP Discovery service did the trick.

Thanks for quick reply, maybe a check on it before starting the app?

**Comment by Hyrules** [comment]
Yes I will try to add a check in the next version.

**Comment by MrRedHead** [comment]
Reopened to add to the program as an enhancement

**Comment by Hyrules** [comment]
Fixed in the next version.
