### ISSUE TITLE
Editing a Light Group Creates a New Group

### ISSUE THREAD

**Issue by OzzieJacks** [Hyrules/WinHue3#69]
When I open an existing light group, add a light to it, and save it the program creates a new group with the same name and light configuration but leaves the original unchanged.

**Comment by Hyrules** [comment]
Noted I will take a look at this.

**Comment by Hyrules** [comment]
Yeah. I can reproduce here to. Will fix this. Thanks for reporting.

**Comment by Hyrules** [comment]
Here is a fixed version. Try it and let me know if it is fixed for you.

[WinHue 3 BETA 26 Setup.zip](https://github.com/Hyrules/WinHue3/files/772663/WinHue.3.BETA.26.Setup.zip)

**Comment by OzzieJacks** [comment]
Yes Beta 26 fixed the problem.  Thank you for fixing it so quickly.
