### ISSUE TITLE
Crashing on schedule edit

### ISSUE THREAD

**Issue by fiveseven808** [Hyrules/WinHue3#7]
Right click on schedule, click on edit, the program crashes. Lemme know if you need logs. Thanks!

**Comment by Hyrules** [comment]
Yes i can reproduce that. Unfortunately this is a bug with WPF Extended toolkit and not WinHue itself. I will check to see if there is a new version for the toolkit otherwise I will change the picker for something else.

**Comment by Hyrules** [comment]
You can try beta 17. I released it just to fix this.

**Comment by fiveseven808** [comment]
Fixed! Thanks!
