### ISSUE TITLE
Adding, editing and deleting of sensors in action-part of rules ends in crash of application 

### ISSUE THREAD

**Issue by xIngenuusx** [Hyrules/WinHue3#70]
Beta_25, Beta_26
Adding, editing and deleting of sensors in action-part of rules ends in crash of application.
For Lights, Groups, Scenes and Schedules all works fine

**Comment by Hyrules** [comment]
Will take a look at this. Thanks for reporting.

**Comment by Hyrules** [comment]
Yep can reproduce will fix asap.

**Comment by xIngenuusx** [comment]
This issue is fixed in postet Version.
Thanks for the good work

**Comment by xIngenuusx** [comment]
Sorry, it appears that this problem has not yet been fully solved. The application today crashed several times when dealing with rules.
I will ty to describe a scenario to reproduce the issue.

**Comment by Hyrules** [comment]
Let me know when you get a scenario where you can trigger this bug again. I will fix it.

**Comment by xIngenuusx** [comment]
Now i got the Scenario:

1. open rule to edit
2. choose any existing (sensor related) Action do edit (list right down)
3. choose any action (list right up)
4. click "Add Action" results in crash

it is not important, but should fixed sometimes

**Comment by Hyrules** [comment]
I think I have this fixed. I'll try to get you a version to test soon.

**Comment by xIngenuusx** [comment]
The bug is fixed for the most parts. 
There is only one new(?) wrong detail
- edit of an Action creates duplicat and error message on save the rule

**Comment by Hyrules** [comment]
Hmmm ok yeah on editing it should edit the action and not add a new one. This is not a bug per se but I will changed this.

**Comment by Hyrules** [comment]
You can try the version in issue #73

**Comment by xIngenuusx** [comment]
All is working fine 
Thanks
