### ISSUE TITLE
Scenes - Preview does not work

### ISSUE THREAD

**Issue by xIngenuusx** [Hyrules/WinHue3#71]
Beta_25, Beta_26
Preview does not work in Create/Edit Scenes

**Comment by Hyrules** [comment]
Will be fixed in the next version.

**Comment by Hyrules** [comment]
Here you go. This should fix both issues you reported. Let me know if everything is ok on your side.

[WinHue 3 BETA 26 Setup.zip](https://github.com/Hyrules/WinHue3/files/778651/WinHue.3.BETA.26.Setup.zip)

**Comment by xIngenuusx** [comment]
This issue is fixed in postet Version.
Thanks for the good work

**Comment by HemiBob** [comment]
I have installed BETA 26 to try and fix this but now, although I can preview scene, it errors if I try and save it. 
Type : 4, method, PUT, not available for resource, /scenes at address /scenes.

See screen capture (is there a way I can cut & paste from the event log, it doesn't work through the clipboard)?)
![scenebug](https://cloud.githubusercontent.com/assets/25841598/23073246/c4e9400c-f52c-11e6-9c73-960c3397aaac.jpg)
