### ISSUE TITLE
Using dx AND checking state in one set of conditions?

### ISSUE THREAD

**Issue by HemiBob** [Hyrules/WinHue3#73]
Should I be able to have the following TWO conditions in one rule?
sensors/4/state/presence = true
sensors/4/state/presence has changed

I'm using a ZLLPresence sensor and I want to have a rule that fires if there is a presence AND the “presence” status has just changed.

However, after entering the second condition a pop-up appears saying that “A similar condition already exists. Replace ?”
“Yes” just replaces the first condition with the second, “No” does nothing.

As a workaround I'm checking for a “dx” state on the lastupdated field but I think you should allow checking a status and a changed condition on the same status.

**Comment by Hyrules** [comment]
You cannot check the same property twice in the same rule. It would be sensor/4/state/presence true AND sensor/4/state/lastupdated dx. You want to check if the sensor has state has changed and if it's now true.

**Comment by HemiBob** [comment]
Many thanks, I was following a suggestion on this page:
https://developers.meethue.com/content/better-rules-motion-sensor
so assumed the hub did allow it and WinHue didn't .
But thanks for checking, Bob.

**Comment by HemiBob** [comment]
Just for your interest, before I found WinHue3 I had installed my motion detector using another app which seems to have done what I'm after and WinHue3 displays it too :-)

![winhue](https://cloud.githubusercontent.com/assets/25841598/23104407/44132e94-f6c5-11e6-9817-fed52b891b8c.jpg)

**Comment by Hyrules** [comment]
This has been changed in the next version.

**Comment by Hyrules** [comment]
see beta in topic #74 and let me know if it works properly on your side.

**Comment by HemiBob** [comment]
Sorry, I couldn't get this version to start up, see log file:
![winhueerror260217](https://cloud.githubusercontent.com/assets/25841598/23338368/f7132086-fc00-11e6-9a8d-aed16ff1e578.jpg)
[WinHue3 LOG.txt](https://github.com/Hyrules/WinHue3/files/801815/WinHue3.LOG.txt)

**Comment by Hyrules** [comment]
Odd... you are missing a dependency dll. This should be included with the setup...

**Comment by HemiBob** [comment]
Loads up and runs now, many thanks.
Modified my rules just fine and no problems yet.
Will continue to test tomorrow.
