### ISSUE TITLE
Integer-Problem on editing rules with sensors in action part

### ISSUE THREAD

**Issue by xIngenuusx** [Hyrules/WinHue3#74]
Creating of new rule works fine and results in action part in:
/sensors/37/state PUT {"Status":1} 
If rule is triggered sensor 37 is set to 1.

On reading from hue-bridge (e.g. reopen WinHue3 or refresh view) the action for sensor37 is shown as:
/sensors/37/state PUT {"Status":"1"}

If i change the rule (e.g. adding an other sensor action it results in 
/sensors/37/state PUT {"Status":"1"}
/sensors/40/state PUT {"Status":2}
If rule is triggered sensor 37 is set to 0 and sensor 40 to 2.

If rule is changed again both actions results in status=0

**Comment by Hyrules** [comment]
I though I had fixed this . I will take a look.

**Comment by Hyrules** [comment]
This should be fixed in the next version.

**Comment by Hyrules** [comment]
Try this version and let me know if it works on your side.

[WinHue 3 BETA 26 Setup.zip](https://github.com/Hyrules/WinHue3/files/801584/WinHue.3.BETA.26.Setup.zip)

**Comment by xIngenuusx** [comment]
I think it is successfull fixed.
Great work, Thanks
