### ISSUE TITLE
Can't select lights to create hotkey

### ISSUE THREAD

**Issue by phantomrtw** [Hyrules/WinHue3#75]
When trying to create a hotkey, I am unable to select lights or groups for the hotkey to control, and thus can not create the hotkey.

![winhue_3_beta_25_2017-02-27_13-52-06](https://cloud.githubusercontent.com/assets/6874352/23374851/fc6385b4-fcf3-11e6-8110-0d2f672a78e9.png)

**Comment by Hyrules** [comment]
I will take a look at this.

**Comment by Hyrules** [comment]
Try this one and let me know if it works on your side :

[WinHue 3 BETA 26 Setup.zip](https://github.com/Hyrules/WinHue3/files/809272/WinHue.3.BETA.26.Setup.zip)

**Comment by phantomrtw** [comment]
Works perfectly. Can add lights, groups and the hotkeys function as they should. Thank you :)
