### ISSUE TITLE
Create a scene causes error

### ISSUE THREAD

**Issue by HemiBob** [Hyrules/WinHue3#77]
Version BETA 26
Click "Create Scene"
Step 1 enter name - OK
Step 2 adjust sliders for Hue, Sat and Brightness, didn't touch Transition Time, Color Temp, XY sliders or the two buttons - OK
Step 3 add three of my six lights - OK, selected lights now appear under "Selected Lights", sliders have all now gone to zero
Click "Save Scene" and this error appears,
![createsceneerror](https://cloud.githubusercontent.com/assets/25841598/23608243/665794b2-0260-11e7-9d7d-f6f0f4f5d61b.jpg)
[WinHue3 2017-03-06.txt](https://github.com/Hyrules/WinHue3/files/820945/WinHue3.2017-03-06.txt)
A quick look at the log mentions that lights are off and therefore settings can't be changed but it's beyond my understanding at the moment.
There is a tick in the "ON" box under the sliders.
Hope this is useful, Bob.

**Comment by HemiBob** [comment]
I have now tried exactly the same method but with all three lights ON before I opened WinHue.
The results are the same

**Comment by Hyrules** [comment]
I will take a look at this.

**Comment by Hyrules** [comment]
Try beta 27 and let me know if it is working for you. It's been released on the main page.

**Comment by HemiBob** [comment]
Yes that’s working now without the error.
Three small points to note when creating a scene.
1) If the Hue/Color slider is left at the bottom (to select red for example), no Hue value is stored because the value at the bottom of the slider is -1, could this be trapped and maybe a value of 317 stored instead?
2) If the selected lights are off when you create the scene, the “Preview” button does nothing, could it turn on those lights for the duration of the preview?
3) I'm not sure what the "Clear" button does
Many thanks for your work

**Comment by Hyrules** [comment]
1) I will see what I can do about this.

2) I will force the on state for preview.

3) The clear button is used when editing a scene or modifying a light state. If you add a light to the scene and want to modify the state afterward you can select it and the state will be displayed so you can modify it.

**Comment by Hyrules** [comment]
I have found a missing assignement for the on property in the scene creator so that's why the scene was not turning the lights on when triggered. I have corrected this.

**Comment by Hyrules** [comment]
Since this is fixed i will close this ticket.
