### ISSUE TITLE
beta27: irritations on editing Groups/Rooms

### ISSUE THREAD

**Issue by xIngenuusx** [Hyrules/WinHue3#79]
Typ should display the correct Typ "Room" or "Light Group" on editing (displays always "Light Group" as default) and should not be editable because it is not possible to change the type after creation.

I know, it is oly "cosmetic" but it would make WinHue 3 more perfect

**Comment by Hyrules** [comment]
Yep I just corrected that. With that I believe that next version will be RC1. Since it's been a while since anyone reported a major functional bug.

**Comment by Hyrules** [comment]
see issue #84 to try a fixed version.
