### ISSUE TITLE
beta27: error on creating and editing of scenes

### ISSUE THREAD

**Issue by xIngenuusx** [Hyrules/WinHue3#80]
in scenes On/Off-State and transitiontime of bulbs are not stored correct.

**Example:**
Before (created with beta24)
`{
  "name": "40-00-01 SleepStop",
  "lights": [
    "1"
  ],
  "owner": "4SVtmKX44suggbY2Wv03CfR3gZq7v9B4l0492Sv6",
  "appdata": {
    "version": 70,
    "data": "PFHS1489270749"
  },
  "recycle": false,
  "locked": false,
  "picture": "",
  "version": 2,
  "lastupdated": "2017-03-22T20:51:30",
  "lightstates": {
    "1": {
      "on": false,
      "transitiontime": 12000
    }
  }
}`

After (editet with beta27)

`{
  "name": "40-00-01 SleepStop",
  "lights": [
    "1"
  ]
  "owner": "4SVtmKX44suggbY2Wv03CfR3gZq7v9B4l0492Sv6",
  "appdata": {
    "version": 70,
    "data": "PFHS1489270749"
  },
  "recycle": false,
  "locked": false,
  "picture": "",
  "version": 2,
  "lastupdated": "2017-03-22T21:07:30",
  "lightstates": {
    "1": {
      "on": true
    }
  }
}`

Transitiontime is permanent set to default and on to true

**Comment by Hyrules** [comment]
Odd I cannot replicate that here. I have created a scene and the value of the transition time is properly sent and edited for the lights the on value is also properly replicated. I have added a missing on setter for the SelectedSceneLight that might not had been updating the value on the form but other than that I cannot replicate the bug.
