### ISSUE TITLE
Default Transition Time

### ISSUE THREAD

**Issue by kinari-01** [Hyrules/WinHue3#81]
Is there a way to change the default transition time?

Personally, I think the transition times feel unresponsive and would prefer them to be always 0.
In an older version of WinHue3 (17), I was able to set them to 0 manually, using the slider. However, this is not possible with the current version.

**Comment by Hyrules** [comment]
No not possible with WinHue 27 but I can easily add this. I will add it to the next version.

**Comment by kinari-01** [comment]
Thank you! <3

**Comment by Hyrules** [comment]
You can try the version in #84 . This version has a setting in the application settings that allow you to set the default transition time.

**Comment by Hyrules** [comment]
Added in the latest version
