### ISSUE TITLE
WinHue unauthorized user

### ISSUE THREAD

**Issue by Vuille** [Hyrules/WinHue3#82]
I had lights turning on without being triggered by any rule or action. I noticed a large number of entries in the white list; some were apparently responsible for unauthorized actions. So, using the API, I removed all entries except one corresponding to me as sole user. The full system continued working fine, in particular all rules and schedules. I could turn lights on and off using the API.
On WinHue, I refreshed the view and everything disappeared from the main window. A note went in the left bottom corner "unauthorized user at address /". I stopped and restarted WinHue. The pairing form appeared; the bridge is detected with its correct IP, but the "Pair" button is grey. No way to go further.
Today's log is attached. How shall I restore the system?
[WinHue3 2017-03-23.txt](https://github.com/Hyrules/WinHue3/files/866126/WinHue3.2017-03-23.txt)

**Comment by Hyrules** [comment]
Basically you remove the authorization of WinHue to acces the bridge. You just have to pair the bridge with WinHue again and it will work. If you want to cleanup the list of unauthorized user you can use WinHue. That way you will not be able to remove WinHue itself from the list of system authorized to access the bridge.

**Comment by Vuille** [comment]
Thank you, everything is OK now. I had to delete the settings in the WinHue folder in order to re-pair WinHue with the bridge.
I appreciate your quick response.

**Comment by Hyrules** [comment]
I will try to add a fix for this in the next version so people do not need to delete the settings file.

**Comment by Hyrules** [comment]
I have unlock the pair button in the next version. Even if it is already paired you will be able to pair it again.

**Comment by Vuille** [comment]
Thank you. When and how to get that new version?

**Comment by Hyrules** [comment]
Not ready yet. I'm still fixing some bugs. Maybe in a couple of days.

**Comment by Hyrules** [comment]
You can try the latest version in issue #84

**Comment by Hyrules** [comment]
Fixed in the latest version.
