### ISSUE TITLE
Misidentified lights

### ISSUE THREAD

**Issue by gabrielepx** [Hyrules/WinHue3#83]
Hello,
WinHue is great and I've used it for a lot of time, thanks for it!
I've noticed a small issue still there in latest beta: a Lightstrip+ and a Bloom light that are showed  with the icon of the normal lamp instead of correct one.

**Comment by Hyrules** [comment]
Can you give me a copy and paste of the josn for those lights ? In WinHue -> Right click the object and copy -> as json formatted. thanks.

**Comment by gabrielepx** [comment]
Il 27/03/2017 22:00, Hyrules ha scritto:
> Can you give me a copy and paste of the josn for those lights ? In WinHue -> Right click the object and copy -> as json formatted. thanks.

Here they are:

LightStrip plus

{
   "state": {
     "reachable": true,
     "on": true,
     "bri": 254,
     "hue": 8478,
     "sat": 143,
     "xy": [
       0.4583,
       0.4113
     ],
     "ct": 365,
     "effect": "none",
     "colormode": "hs",
     "alert": "select"
   },
   "type": "Extended color light",
   "manufacturername": "Philips",
   "name": "LS+ salotto",
   "modelid": "LST002",
   "swversion": "5.50.2.19072",
   "uniqueid": "00:17:88:01:01:1f:f4:41-0b"
}


Bloom

{
   "state": {
     "reachable": true,
     "on": true,
     "bri": 254,
     "hue": 2162,
     "sat": 254,
     "xy": [
       0.6858,
       0.3126
     ],
     "effect": "none",
     "colormode": "xy",
     "alert": "none"
   },
   "type": "Color light",
   "manufacturername": "Philips",
   "name": "Bloom camera",
   "modelid": "LLC011",
   "swversion": "5.23.1.13452",
   "uniqueid": "00:17:88:01:00:c5:53:74-0b"
}



-- 
Saluti da Gabriele Favrin
http://www.favrin.net

**Comment by Hyrules** [comment]
That's simple. If you want them to match the images just go into winhue folder and copy the images and rename them to match modelid. So copy the lightstrip images (the 3 images) (LST001) and rename them to LST002_unr.png LST002_on.png and LST002.off.png and next time you restart WinHue it will show the proper icons for that model. Repeat the the bloom.

**Comment by Hyrules** [comment]
Modified in the latest version.
