### ISSUE TITLE
Editing a schedule causes winhue3 to exit

### ISSUE THREAD

**Issue by wo-rasp** [Hyrules/WinHue3#84]
I have a schedule, i can edit it, but when i try to save it winhue3 (Beta 27) terminates.
I upgraded from Beta 19 to 27, e.q. the schedule was created with Beta 19.
![grafik](https://cloud.githubusercontent.com/assets/7294039/24634421/2eb14d44-18ce-11e7-89e1-20a94510f25a.png)

**Comment by Hyrules** [comment]
Can you give me the json code of the schedule ? right click the object and copy as json formatter.

**Comment by wo-rasp** [comment]
Originally i had two groups, Group 0 and Group 1 and was controlling everything from my Windows Phone.

Later on this got extended with the room concept used by the new iOS App.

 

My problem is to disable the schedule „Licht An“, as it is supposed to turn the lights on in the morning at a fixed time and to turn them off after sunrise, but during summertime I do not want to turn them on in the morning

 

Thus I simply wanted to turn the schedule off and disable it, I can call the menu using the edit command, but any SAVE will fail.

 

This is the schedule

{

  "name": "Licht An",

  "localtime": "W127/T06:55:00",

  "description": "Group 1",

  "time": "W127/T04:55:00",

  "command": {

    "method": "PUT",

    "address": "/api/ZHijQCVS039Gcjf4XaAVcwUxktaMfGxf3HmFgm8p/groups/1/action",

    "body": {

      "bri": 160,

      "transitiontime": 20,

      "on": true

    }

  },

  "status": "enabled",

  "recycle": false,

  "created": "2016-12-30T23:48:21"

}

 

This is Group 1:

{

  "action": {

    "on": false,

    "bri": 160,

    "alert": "none"

  },

  "state": {

    "all_on": false,

    "any_on": false

  },

  "lights": [

    "2",

    "3",

    "4"

  ],

  "name": "Group 1",

  "type": "LightGroup"

}

 

These are the Lamps associated with Group1:

{

  "state": {

    "reachable": true,

    "on": false,

    "bri": 160,

    "alert": "none"

  },

  "type": "Dimmable light",

  "manufacturername": "Philips",

  "name": "Eingang",

  "modelid": "LWB006",

  "swversion": "5.38.2.19136",

  "uniqueid": "00:17:88:01:10:5c:37:41-0b"

}

{

  "state": {

    "reachable": true,

    "on": false,

    "bri": 160,

    "alert": "select"

  },

  "type": "Dimmable light",

  "manufacturername": "Philips",

  "name": "Sekretaer",

  "modelid": "LWB006",

  "swversion": "5.38.2.19136",

  "uniqueid": "00:17:88:01:02:08:58:90-0b"

}

{

  "state": {

    "reachable": true,

    "on": false,

    "bri": 160,

    "alert": "none"

  },

  "type": "Dimmable light",

  "manufacturername": "Philips",

  "name": "Buero",

  "modelid": "LWB006",

  "swversion": "5.38.2.19136",

  "uniqueid": "00:17:88:01:10:36:d3:53-0b"

}

 

Could the problem be with the authentification address of WINHUE ?

The reason why I suspect this:

The schedule is using an address that is known to the bridge, but that addressis not associated with WINHUE.

That address is associated with HUETRO#HUETRO(WP) –> I assume an older authentification with my Windows Phone.

I do not remember whether I creates the schedule with WINHUE or with the Windows Phone ….

 

Von: Hyrules [mailto:notifications@github.com] 
Gesendet: Dienstag, 4. April 2017 00:39
An: Hyrules/WinHue3
Cc: wo-rasp; Author
Betreff: Re: [Hyrules/WinHue3] Editing a schedule causes winhue3 to exit (#84)

 

Can you give me the json code of the schedule ? right click the object and copy as json formatter.

**Comment by Hyrules** [comment]
Quite possible. If WinHue is trying to modify an schedule created by another app this might end up crashing the app. I will take a look at this tonight.

**Comment by wo-rasp** [comment]
Is it possible to import a (modified) JSON object ?

**Comment by Hyrules** [comment]
Right now there is no way to import an json object. Winhue IOS does not exists to my knowledge or if it is i'm not the programmer. The Philips Hue Api does not allow modification of a schedule created by other app.

**Comment by wo-rasp** [comment]
The Huetro App for WP does not allow it either and reports that the Alarm needs to be deleted and recreated. In theory a lot is possible, but I think it is best to add this behaviour to Winhue as well.

**Comment by wo-rasp** [comment]
I have deleted all old Alarms. The are also gone on the HUETRO App.
When I try to create a new Alarm or a new Timer for Group 1 or any of the lamps, Winhue 3 terminates, when i try to create a new schedule Winhue 3 stops with the following error message (and remains alive):
![grafik](https://cloud.githubusercontent.com/assets/7294039/24696752/d0c98552-19ea-11e7-909c-7e74177beb26.png)

**Comment by Hyrules** [comment]
I know there is an issue I fixed with the autodelete. I will try to get you a version to test soon. I have already made some changes to WinHue and it might fix it.

**Comment by Hyrules** [comment]
Hmm ok got it. I found the exception. I'll correct it.

**Comment by Hyrules** [comment]
Here is the latest version : https://1drv.ms/u/s!AtzSAzkJ1YCtgbBkEOVNBh6UdclX1w
You can download it on my one drive since GitHub does not seems to want to take exe inside zip anymore.
Let me know if this is fixed on your side.

**Comment by wo-rasp** [comment]
The RC1 has fixed my previous problems.

**Comment by Hyrules** [comment]
Great. FYI the settings of the app might not work correctly as i'm currently rewriting them.

**Comment by wo-rasp** [comment]
I noticed that reporting of parameters is not consistent, however that was less of a concern. In particular the randomize parameter seems to be preset.

Von meinem iPhone gesendet

**Comment by Hyrules** [comment]
Can you elaborate on that ? What do you mean by parameters inconsistent ? Other than the randomize.

**Comment by Hyrules** [comment]
This issue is fixed you can open a new issue for the inconsistency
