### ISSUE TITLE
Cann't create a schedule

### ISSUE THREAD

**Issue by r-sch** [Hyrules/WinHue3#85]
Using BETA 27 I cann't create a schdule. The menu is grayed out.

![grafik](https://cloud.githubusercontent.com/assets/27267649/24894750/a62038ea-1e8c-11e7-9c66-6bdf0cf4a16e.png)

What's wrong? Thank you for help.

**Comment by Hyrules** [comment]
Did you click on on an object before creating a schedule ? You have to select a light, group et scene to create a schedule.

**Comment by r-sch** [comment]
That was the problem. It works as you described. Thank you for your quick help.
