### ISSUE TITLE
Rules and motion sensor

### ISSUE THREAD

**Issue by gabrielepx** [Hyrules/WinHue3#87]
When creating a rule to affect a motion sensor, I can't select config, eg. to enable/disable motion sensor with tap.

On this matter, it would be useful to have a raw input mode, to be able to input stuff even when WinHue don't yet support some options.

**Comment by Hyrules** [comment]
The raw imput mode is an interesting Idea. I could add a window where the user could literally type the json for the object and send it to the bridge. Otherwise I will add the option to disable and enable sensors in the rule creator.

**Comment by Hyrules** [comment]
Added an advanced creator in the lastest version let me know if there is anything else.
