### ISSUE TITLE
Can't setup hotkeys

### ISSUE THREAD

**Issue by Krevitzz** [Hyrules/WinHue3#89]
Hi, and thanks for this app.
I'm trying to create a system of hotkeys to control my hue lights
(kind of 8 + '+' to increase the luminosity of light number 8)
My problem is i can't create even a single hotkey as the recorder doesn't seems to work, only take in account the last entry of the sequence, write "none + the last entry" in the box and the button "add hotkey" stay gray. 
Is there a way to fix the problem? plz

**Comment by Hyrules** [comment]
Which version are you using?

**Comment by Krevitzz** [comment]
Winhue 3, i just updated..

2017-05-25 1:26 GMT+02:00 Hyrules <notifications@github.com>:

**Comment by Hyrules** [comment]
I meant beta 25, 26 , 27 ? RC1 ?

**Comment by Krevitzz** [comment]
oh sorry, it's RC1

2017-05-25 12:35 GMT+02:00 Hyrules <notifications@github.com>:

**Comment by Hyrules** [comment]
ok try using a ctrl key instead of a normal key. This is not a bug i made it that way. The first key is a modifier key like ctrl alt or shift the second is a normal key. you cannot use 2 normal keys.

**Comment by Krevitzz** [comment]
Thanks it is working :)
well kinda i setup ctrl + number x to get increase luminosity on the lamp
x, Ctrl shift x to decrease
From off it does light up
From on it does light off
I have huge amount of latency
Am i missing something again?

2017-05-25 12:39 GMT+02:00 Hyrules <notifications@github.com>:

**Comment by Hyrules** [comment]
It might depend on your setup. When you send other commands with WinHue do you have any latency ?

**Comment by Krevitzz** [comment]
Not as much, if i slide the luminosity cursor with the mouse the change
occur less than a second after i let the mouse button go, if i click then
use the arrows on the bar nothing appends or much later...

2017-05-25 14:56 GMT+02:00 Hyrules <notifications@github.com>:

**Comment by Hyrules** [comment]
I will have to take a look at the code and see if there is a latency of any kind for registering the key and action. It might be a good idea to add a visual indicator to see if a key has been registered in the app.

**Comment by Krevitzz** [comment]
Thank you :)

2017-05-25 19:47 GMT+02:00 Hyrules <notifications@github.com>:

**Comment by Hyrules** [comment]
Added the indicator in the latest version let me know if there is anything else.
