### ISSUE TITLE
Automatic Colour Change Mode:

### ISSUE THREAD

**Issue by D1311** [Hyrules/WinHue3#90]
Philips LivingColors has this mode, would it be possible to get on winhue. Iwould love to be able to do this with winhue as I seem to be able to only use the controller or winhue.

You can also let your LivingColors change colours automatically. You can even choose how fast you want it to go through the whole colour
spectrum.
Sweep your fnger clockwise around the colour wheel (one full circle, 360) and brieﬂy press on “I” (“On”) to get into the Automatic
Colour Change Mode. The LivingColors will now start looping through the colours.
Change the speed of the Automatic Colour Change Mode stepwise (20 steps in total) by sweeping the colour wheel clockwise (to go
faster) or anticlockwise (to go slower) for 90° during the time that the Automatic Colour Change Mode is on.
![automatic colour change mode](https://cloud.githubusercontent.com/assets/28877894/26493811/92a79e70-4213-11e7-8626-7d4099847a86.jpg)

**Comment by Hyrules** [comment]
yes it's easy to do. You just have to set the effects to color loop. I just forgot to add it to WinHue 3. It was already present in older previous versions link WinHue 2 and 1.

**Comment by D1311** [comment]
Downloaded winhue2 but will not connect to bridge, any chance this could be added to winhue 3 if it is easy. Or could you give an example of how to do coloue loop.
Thanks

**Comment by Hyrules** [comment]
I will add it to winhue 3 in the next release. To active the color loop you have to send a command to the bridge by setting the effect to colorloop. You cannot really do it in WinHue right now. You have to use an external tool to send command to your bridge.

**Comment by D1311** [comment]
K , thanks I look forward to next release.
Thank you again

**Comment by Hyrules** [comment]
just something I want to clarify. I'm implementing the colorloop function already in the bridge. This color loop happens when you set the effect of a light or a group to colorloop. There is no way you can control the speed. it will go through all color but at a predefined speed.

**Comment by D1311** [comment]
K, thanks for letting me know. When will I be able to download it.

**Comment by Hyrules** [comment]
Unfortunately I don't know. Since i'm the only dev on this project plus I don't have alot of time lately to code, it may take some time before I publish a new version. I have not abandoned anything I just have less time.

**Comment by D1311** [comment]
Looking forward to it, How can I get winhue 2 to connect.

**Comment by Hyrules** [comment]
Mostlikely not. Bridge has changed so much since WinHue 2 that it will simply not work.

**Comment by D1311** [comment]
Is it possible to put this on a timer so it can come on at a certain time and go off at a certain time and if so how do I do it.

**Comment by D1311** [comment]
Job done,
