### ISSUE TITLE
Schedules

### ISSUE THREAD

**Issue by Dave3755** [Hyrules/WinHue3#91]
I create a schedule and regardless of what I leave selected in AutoDelete it always is enabled in properties when I look.  Therefore it gets deleted once executed and I have to recreate it.  I'm simply trying to get 2 lights to go on and off while on vacation w/o having the create 40+ tasks.  Any hints for a newbie?

**Comment by Hyrules** [comment]
this is a known issue. It will be fixed in the next iteration see issue #84
