### ISSUE TITLE
Console application throws an exception when using any parameters

### ISSUE THREAD

**Issue by tzorca** [Hyrules/WinHue3#92]
whc.exe shows this message when specifying any parameters (even just -h):
"The type initializer for 'whc.WinHueSettings' threw an exception."

Happens with version WinHue 3 RC1. I tried using version WinHue 3 BETA 26, and that version worked as expected.

I checked the log file, but did not see any additional information about the exception.

**Comment by Hyrules** [comment]
hi have not updated whc in a while. my computer motherboard is currently on
rma so i cannot do any type of coding. i will take a look as soon as my
computer is fixed.

**Comment by edemaine** [comment]
Same issue here.

**Comment by Hyrules** [comment]
Should be fixed in the latest version.
