### ISSUE TITLE
Is there a way to have a flag set whenever a certain device on the network hasn't been active for a certain amount of time?

### ISSUE THREAD

**Issue by sunbear87** [Hyrules/WinHue3#93]
I want to be able to have a sensor which turns to true after my desktop or laptop (windows 10) has been inactive for a certain time. Or perhaps just when it locks or goes to sleep.

The idea is that I have certain rules that activate scenes. But I only want them to activate when I am using my computer.

Is this possible?

**Comment by Hyrules** [comment]
Your computer has to set the flag in the sensor himself. There is no other way to do this. There are automation softwares that can probably do that.
