### ISSUE TITLE
Delay is not saved when creating a schedule

### ISSUE THREAD

**Issue by sunbear87** [Hyrules/WinHue3#94]
If I create a schedule/event/alarm with a certain delay in the delay field, it has no effect when it is activated. Also, whenever I click to edit the schedule, the delay field is always empty.

**Comment by Hyrules** [comment]
Thanks for reporting this. I will take a look as soon as my motherboard is back from RMA. My main computer is not working at the moment so I cannot code anything or correct any bugs.

**Comment by Hyrules** [comment]
OK got my motherboard back. By delay you mean the Transition time ?

**Comment by Hyrules** [comment]
I have corrected the delay not showing when editing a schedule. Other than that the delay seems to be working properly here. Are you sure you are calculating your delay properly ? the value you enter is multiplied by 100 so if you enter 50 it's going to take 5 seconds for the transition to happen.

**Comment by Hyrules** [comment]
Should be fixed in the latest version.
