### ISSUE TITLE
Xiaomi Philips Smart LED Ball Lamp

### ISSUE THREAD

**Issue by D1311** [Hyrules/WinHue3#96]
Not sure if this is possible as I bought this lamp (link below) as someone said it work with Hue but the only thing that seems to work is mihome if Chinese is set for home settings. I not that savvy when it comes to apps, well I don't even have a mobile, that's why I love your app. Even so I have only used alarm so far.

http://www.gearbest.com/smart-lighting/pp_644095.html?wid=21&utm_source=tt_de

**Comment by Hyrules** [comment]
Hard to tell did you try to scan for new devices or lights ?

**Comment by D1311** [comment]
yeah could not find it.

**Comment by Hyrules** [comment]
from what I read on the web this light seems to be wireless and not zigbee. The Philips hue bridge is ZigBee so that's most likely the reason you cannot see it in WinHue and the bridge.

**Comment by D1311** [comment]
dang it, thought itr was too good to be true.
Thanx
