### ISSUE TITLE
whc: Group specification ignored

### ISSUE THREAD

**Issue by edemaine** [Hyrules/WinHue3#98]
`whc -g Bedroom --on=false` turns off all lights in my system, not just those in the group.  Ditto for `whc --group=Bedroom --on=false` and similarly for `-on=true`.  It seems that the group specification is ignored, other than the printed message which says:

```
Group action sent succesfully to group : Bedroom
```

(tested in WinHue 3 Beta 15 and 27, RC1 has issue #92)

**Comment by Hyrules** [comment]
thanks for reporting this I will take a look.

**Comment by Hyrules** [comment]
you cannot specify the group name as the group you want to change the state. You have to send it's id. Groups ID are numbers.

**Comment by edemaine** [comment]
Oh, I see!  That works well.

Perhaps it would make sense to document this somewhere...  (It may have been in the command-line help -- but now `whc` and `whc -help` produce `The handle is invalid.` in v3 Beta 27.)
