### ISSUE TITLE
Applying a Scene to a Group as a Rule Action does not work

### ISSUE THREAD

**Issue by banksio** [Hyrules/WinHue3#99]
When I type the name of a scene and press 'Add', the scene name just defaults to '1'.
![image](https://user-images.githubusercontent.com/30214760/28248847-3fd3bce4-6a43-11e7-90a6-d9cd7a7a2d16.png)
After clicking 'Add'...
![image](https://user-images.githubusercontent.com/30214760/28248851-546eae70-6a43-11e7-98b8-6d4208051754.png)

**Comment by Hyrules** [comment]
Thanks for reporting this. I will not fix this bug since the Rule creator is going to change in the next version. I'm trying to build something more simple to use. It should be available in the next release. I cannot say when because i'm revamping the whole code at the moment simplifying stuff and removing some layers and recoding some part of the application.

**Comment by banksio** [comment]
Thanks for letting me know, will be cool to see the new version.

**Comment by Hyrules** [comment]
Try the latest version and let me know if everything is in order

**Comment by banksio** [comment]
Hi Hyrules,

The new editor works great, except that it crashes when I try to select certain rule objects.
[Here's a video](https://youtu.be/ZmuWC9lMZto) of the issue and [here's the log file](https://pastebin.com/JRBptpBK) corresponding to the video (I've changed my bridge's MAC to a fake one).

Thanks!

**Comment by Hyrules** [comment]
I'll take a look at this. thanks fro reporting it. Most likely something I forgot to implement by the exception.

**Comment by Hyrules** [comment]
hmm ok the storelightstate is causing the problem. I'll have to thing a way to correct this.

**Comment by Hyrules** [comment]
RC3 release let me know if this issue is still occuring.

**Comment by banksio** [comment]
@Hyrules I'll check as soon as I can.
